### ISSUE TITLE
vscode.proposed.d.ts:1499:3 - error TS2374: Duplicate string index signature.

### ISSUE THREAD

**Issue by sherryyshi** [microsoft/vscode#87198]
The latest proposed.d.ts contains this error: `vscode.proposed.d.ts:1499:3 - error TS2374: Duplicate string index signature.`

Seems to have been introduced by 48f20cbdaa497a4b91212418a7703c0dd0b405cb

**Comment by sherryyshi** [comment]
Looks like it's because `readonly [key: string]: any;` in `WorkspaceConfiguration` is defined in both vscode.d.ts and vscode.proposed.d.ts, which causes issues when the interfaces are merged.

Check out this snippet for a repro of this error: https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgBIQDYYPbIN4BQUEcAJtiBgJ7LECOArsMaQMphSgDmAXMgM4duAbiIlylGgG0A1hCp9BnEFwC6fOCCqiAvgWQFQkWIhTosuQsTIVqtCI2YQ2QlQCZFrrqOsS7s+U9lNQ0tXX0CBApBZDg+cxxkAF58fWR0+iYWdmC+AHIAeRAIPIAaNIyHLOcc7g9kPIAVAHdsPIIdIA
