### ISSUE TITLE
Activating extension 'vscode.extension-editing' failed

### ISSUE THREAD

**Issue by mentat9** [microsoft/vscode#102180]
- VSCode Version: 1.48.0-insider
- OS Version: 2004 (OS Build 19041.329)

Steps to Reproduce:

1. I don't have specific details: the issue appears to occur from code running in my extension.

Does this issue occur when all extensions are disabled?: Yes/No
No

This error is thrown:

```
Activating extension 'vscode.extension-editing' failed: Cannot find module 'd:\OneDrive\Tools\dev\vscode\1.48.0-insider\resources\app\extensions\extension-editing\dist\extensionEditingMain'
Require stack:
- d:\OneDrive\Tools\dev\vscode\1.48.0-insider\resources\app\out\vs\loader.js
- d:\OneDrive\Tools\dev\vscode\1.48.0-insider\resources\app\out\bootstrap-amd.js
- d:\OneDrive\Tools\dev\vscode\1.48.0-insider\resources\app\out\bootstrap-fork.js.
```

I'm assuming this is a built-in extension (it's not one I installed nor do my extensions depend on it). Looks like possibly a build problem: the **<root>\resources\app\extensions\extension-editing\dist** folder is present, but the **<root>\resources\app\extensions\extension-editing\out** folder is not.

**Comment by janhartmann** [comment]
Can confirm that I see the same:

```[2020-07-13 13:59:33.896] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/extension-editing/dist/extensionEditingMain
[2020-07-13 13:59:33.897] [exthost] [error] Activating extension vscode.extension-editing failed due to an error:
[2020-07-13 13:59:33.900] [exthost] [error] Error: Cannot find module '/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/extension-editing/dist/extensionEditingMain'
Require stack:
- /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
	at Module._load (internal/modules/cjs/loader.js:691:27)
	at Function.Module._load (electron/js2c/asar.js:748:26)
	at Function.t._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:991:657)
	at Function.i._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:961:661)
	at Function.n._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:957:966)
	at Module.require (internal/modules/cjs/loader.js:853:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Function.s [as __$__nodeRequire] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:33:604)
	at h._loadCommonJSModule (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:962:842)
	at h._doActivateExtension (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:865:367)
	at h._activateExtension (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:864:453)
	at Object.actualActivateExtension (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:862:230)
	at h._activateExtension (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:607:405)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:607:83
	at Array.map (<anonymous>)
	at h._activateExtensions (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:607:71)
	at h.activateByEvent (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:604:546)
	at h._activateByEvent (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:863:122)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:871:693
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2020-07-13 14:00:54.855] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2020-07-13 14:00:54.855] [exthost] [error] Error: DisposableStore is missing...
	at U._convertCompletionItem (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:686:365)
	at U.resolveCompletionItem (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:686:132)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2020-07-13 14:04:06.709] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.references-view {"startup":false,"extensionId":{"value":"ms-vscode.references-view","_lower":"ms-vscode.references-view"},"activationEvent":"onCommand:editor.action.showReferences"}
[2020-07-13 14:04:06.709] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.references-view/dist/extension```

**Comment by bradennapier** [comment]
Same - in addition `rename symbol` randomly no longer works so guessing it is related?

```
Error: Cannot find module '/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/extension-editing/dist/extensionEditingMain'
Require stack:
- /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Function.t._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:991:657)
    at Function.i._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:961:661)
    at Function.n._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:957:966)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by StephenWeatherford** [comment]
Same

**Comment by dbaileyut** [comment]
This is weird, I encountered it after upgrading:

```
Version: 1.47.1 (system setup)
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:42:53.386Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```

I reproduced it on two different Windows 10 machines when I ran Code as administrator **and** as a different user. E.g. right clicked in Start menu, chose Run As Administrator, then entered credentials for a different user. I could not reproduce when logging into Windows directly as that administrator user - whether Code was elevated to an administrator or not. Using runas.exe un-elevated from the admin user to run as my un-privileged account did not show the problem.

I could not reproduce with the Insiders build below, so maybe it's fixed? I ran the user setup version of Insiders first under each user and then tried the system setup version. After that the problem seems to have gone away on the first machine **on 1.47.1 somehow**. I'm not going to try Insiders on the second machine to be able to reproduce the problem.

```
Version: 1.48.0-insider (system setup)
Commit: c828a5339bca7222fd8f56ab98361a98f736d185
Date: 2020-07-14T05:39:53.264Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19041
```

Developer console shows:
```
abstractExtensionService.ts:411 Activating extension 'donjayamanne.githistory' failed: The "path" argument must be of type string. Received type undefined.
_logMessageInConsole @ abstractExtensionService.ts:411
abstractExtensionService.ts:411 Activating extension 'eamodio.gitlens' failed: The "path" argument must be of type string. Received type undefined.
_logMessageInConsole @ abstractExtensionService.ts:411
abstractExtensionService.ts:411 Activating extension 'HookyQR.beautify' failed: The "path" argument must be of type string. Received type undefined.
_logMessageInConsole @ abstractExtensionService.ts:411
abstractExtensionService.ts:411 Activating extension 'Shan.code-settings-sync' failed: The "path" argument must be of type string. Received type undefined.
_logMessageInConsole @ abstractExtensionService.ts:411
abstractExtensionService.ts:411 Activating extension 'streetsidesoftware.code-spell-checker' failed: The "path" argument must be of type string. Received type undefined.
_logMessageInConsole @ abstractExtensionService.ts:411
abstractExtensionService.ts:411 Activating extension 'ms-vscode.powershell' failed: The "path" argument must be of type string. Received type undefined.
```

Not reproducible without extensions but I tried uninstalling everything except "ms-vscode.powershell".

**Comment by dbaileyut** [comment]
Reproduced after the upgrade to 1.47.1 on a 3rd machine. Haven't been able to clear the error state in 1.47.1 by installing the Insiders build. So I'm not sure how I got it running on the first machine.

**Comment by dbaileyut** [comment]
Also appears similar to #102686

**Comment by mentat9** [comment]
My repro is definitely different from #102686. I cannot repro the failure when launching as admin. Here's some updated repro info I've discovered:
* Only repros on instances launched as a debug target from the [VSCode] debugger.
* Repros both the same whether launched as admin or standard.
* Happen when the first .json file or .ts file is opened (again, this only happens in the debug target).
* Does not happen when opening .txt, .cs, .resource, .csproj files.

Here are reliable repro steps in my environment:
1. Launch VSCode version 1.48.0-insider from a command shell in a project folder.
2. Hit F5 to launch the debugger.
3. From the debug target instance, open a .json or .ts file.
4. Observe the error alert described above:
*Activating extension 'vscode.extension-editing' failed: Cannot find module 'd:\OneDrive\Tools\dev\vscode\1.48.0-insider\resources\app\extensions\extension-editing\dist\extensionEditingMain'*

**Comment by alexdima** [comment]
This was introduced via db0d3f089d019961b2f2b1eaca3cff0bba0612c7 and fixed via 717272507d5ccb84e89374125b0511a6a8008f9c. I have verified Stable and it is OK and the latest insiders is also OK.
