### ISSUE TITLE
ELECTRON_RUN_AS_NODE is removed too late before bootstrap-amd.js redefines 'fs'

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#225139]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: stable
- OS Version:

Steps to Reproduce:

Regression from https://github.com/microsoft/vscode/pull/221154 

This broke my extension as I invoke the server-cli, now I get
```
2024-08-08 13:26:09.718 [error] Failed to initialize remote extensions: Loading "original-fs" failed
Error: Cannot find module 'original-fs'
Require stack:
- /home/gitpod/.vscode-server/bin/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
```

cc @bpasero could this be fixed in recovery please

**Comment by bpasero** [comment]
@jeanp413 I am sorry for the regression but if you care about a speedy fix, you need to provide some steps for me to reproduce this issue. I see a stacktrace in your description, but no steps.

And as for recovery, I think at least for this week we cannot put a fix in.

**Comment by jeanp413** [comment]
Steps:
1. run `export ELECTRON_RUN_AS_NODE=1`;
2. run `server-cli --status`

The issue is that `const bootstrapAmd = require('./bootstrap-amd');` is done before `delete process.env['ELECTRON_RUN_AS_NODE'];` in `server-cli.js`

cc @bpasero

**Comment by bpasero** [comment]
I am wondering how this surfaces as an issue, to my knowledge to date this is the first issue about it. For this to qualify as a candidate next week it would need to impact many people 🤔

**Comment by mjrist** [comment]
@bpasero I am having the same problem. My extension can no longer invoke code.
See https://github.com/microsoft/vscode/issues/224498#issuecomment-2276373351
And https://github.com/microsoft/vscode/issues/224498#issuecomment-2264888560

**Comment by bpasero** [comment]
Yeah but I am not sure if that is the same issue, did you test with our just released recovery release `1.92.1`?

**Comment by mjrist** [comment]
Yes I am using 1.92.1.

As described by ernestoalejo https://github.com/microsoft/vscode/issues/224498#issuecomment-2264888560, if I run `delete env.ELECTRON_RUN_AS_NODE` before I exec code it works.

I'm not sure why I need to do that or what the implications are though.
