### ISSUE TITLE
ExtHostLanguageFeatureCommands unit tests: Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#154268]
Running unit tests on Windows gives a lot of warnings in the `ExtHostLanguageFeatureCommands` suite

```
  ExtHostLanguageFeatureCommands
    + WorkspaceSymbols, invalid arguments
[21280:0706/064114.553:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064114.553:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064114.554:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064114.554:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064114.571:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + WorkspaceSymbols, back and forth
[21280:0706/064114.601:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064114.618:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + executeWorkspaceSymbolProvider should accept empty string, #39522
[21280:0706/064114.650:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + executeFormatDocumentProvider, back and forth
[21280:0706/064114.684:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + vscode.prepareRename
[21280:0706/064114.716:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + vscode.executeDocumentRenameProvider
    + Definition, invalid arguments
[21280:0706/064114.741:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064114.741:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064114.742:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064114.742:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064114.763:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Definition, back and forth
[21280:0706/064114.797:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Definition, back and forth (sorting & de-deduping)
[21280:0706/064114.826:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Definition Link
[21280:0706/064114.857:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Declaration, back and forth
[21280:0706/064114.887:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Declaration Link
    + Type Definition, invalid arguments
[21280:0706/064114.914:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064114.914:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064114.915:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064114.915:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064114.934:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Type Definition, back and forth
[21280:0706/064114.966:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Type Definition Link
    + Implementation, invalid arguments
[21280:0706/064114.993:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064114.993:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064114.994:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064114.994:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064115.013:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Implementation, back and forth
[21280:0706/064115.046:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Implementation Definition Link
[21280:0706/064115.072:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + reference search, back and forth
[21280:0706/064115.105:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Outline, back and forth
[21280:0706/064115.139:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + vscode.executeDocumentSymbolProvider command only returns SymbolInformation[] rather than DocumentSymbol[] #57984
[21280:0706/064115.172:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Suggest, back and forth
[21280:0706/064115.204:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Suggest, return CompletionList !array
[21280:0706/064115.235:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Suggest, resolve completion items
[21280:0706/064115.271:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + "vscode.executeCompletionItemProvider" doesnot return a preselect field #53749
[21280:0706/064115.303:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + executeCompletionItemProvider doesn't capture commitCharacters #58228
[21280:0706/064115.332:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + vscode.executeCompletionItemProvider returns the wrong CompletionItemKinds in insiders #95715
[21280:0706/064115.368:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Parameter Hints, back and forth
[21280:0706/064115.401:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + QuickFix, back and forth
[21280:0706/064115.429:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + vscode.executeCodeActionProvider results seem to be missing their `command` property #45124
[21280:0706/064115.460:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + vscode.executeCodeActionProvider passes Range to provider although Selection is passed in #77997
[21280:0706/064115.492:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + vscode.executeCodeActionProvider results seem to be missing their `isPreferred` property #78098
[21280:0706/064115.529:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + resolving code action
[21280:0706/064115.568:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + CodeLens, back and forth
[21280:0706/064115.600:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064115.615:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + CodeLens, resolve
[21280:0706/064115.645:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Links, back and forth
[21280:0706/064115.677:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064115.689:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + What's the condition for DocumentLink target to be undefined? #106308
[21280:0706/064115.731:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064115.742:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Color provider
[21280:0706/064115.774:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + "TypeError: e.onCancellationRequested is not a function" calling hover provider in Insiders #54174
[21280:0706/064115.805:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Inlay Hints, back and forth
[21280:0706/064115.837:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Inline Hints, merge
[21280:0706/064115.866:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Inline Hints, bad provider
[21280:0706/064115.899:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + Selection Range, back and forth
[21280:0706/064115.931:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064115.942:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064115.952:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + CallHierarchy, back and forth
[21280:0706/064115.984:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + prepareCallHierarchy throws TypeError if clangd returns empty result #137415
[21280:0706/064116.016:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064116.026:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
[21280:0706/064116.037:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + TypeHierarchy, back and forth
[21280:0706/064116.067:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + selectionRangeProvider on inner array always returns outer array #91852
[21280:0706/064116.096:INFO:CONSOLE(63)] "Uncaught (in promise) TypeError: this._extensionService.activationEventIsDone is not a function", source: file:///C:/Github/microsoft/vscode/out/vs/workbench/api/browser/mainThreadCommands.js (63)
    + selectionRangeProvider on inner array always returns outer array #91852
```
