### ISSUE TITLE
Cannot debug extension (r.filter is not a function).

### ISSUE THREAD

**Issue by plisy** [microsoft/vscode#80719]
- OS Version: Darwin x64 18.7.0
- VSCode Version: 1.39.0-insider

Commit: 211fa02efe8c041fd7baa8ec3dce199d5185aa44
Date: 2019-09-11T06:12:03.831Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0

Steps to Reproduce:

1. Open extension in VSCode
2. Select Launch Configuration

```json
{
    "name": "Launch Extension",
    "type": "extensionHost",
    "request": "launch",
    "runtimeExecutable": "${execPath}",
    "args": [
        "--extensionDevelopmentPath=${workspaceRoot}",
        "--folder-uri",
        "vscode-remote://<custom_resolver_authority>"
    ],
    "stopOnEntry": false,
    "sourceMaps": true,
    "outFiles": [
        "${workspaceRoot}/out/prod/**/*.js"
    ],
    "preLaunchTask": "build",
    "smartStep": true
}
```
3. See error `Cannot debug extension (r.filter is not a function).`

![image](https://user-images.githubusercontent.com/1951942/64706318-27250100-d466-11e9-89fd-80ce068eae94.png)

> `build` preLaunchTask passed

Does this issue occur when all extensions are disabled?: Yes

cc @isidorn Please take a look.

**Comment by isidorn** [comment]
@plisy was this actually working before?
The issue is that i can not reproduce.

Looking at the error message it is coming from [here](https://github.com/Microsoft/vscode-node-debug2/blob/965054f347a8f4ea4a690f82083e9ad8f708633e/src/nodeDebugAdapter.ts#L282) so it seems like NodeDebug2 tried to Launch VS Code and failed.

@roblourens and @aeschli might have changes something in that area recently

fyi @weinand

**Comment by plisy** [comment]
Works like a charm on version:

Version: 1.38.0-insider
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T23:11:54.533Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by isidorn** [comment]
Ok, so let's wait for @aeschli and @roblourens to comment.
If nobody nows what broke it you can send me better repro steps on mail inikolic@microsoft.com and I can bysect commits to find the breakage.

**Comment by weinand** [comment]
@plisy does it make a difference if you remove the `"--folder-uri", "vscode-remote://<custom_resolver_authority>"` from the launch config?

What is the purpose of that anyway?

@aeschli you worked on argument parsing, most likely that has an effect on the `"--folder-uri", "vscode-remote://<custom_resolver_authority>"`, right?

**Comment by plisy** [comment]
Yes, that worked.

**Comment by weinand** [comment]
Aha, now I understand.
So basically you want to debug a remote authority resolver extension and in order to trigger this resolver you are passing a workspace folder-uri with the desired authority.

I will look into this problem and try to find a solution.

**Comment by jasongin** [comment]
That’s not important. Debugging the resolver works if we first launch normally (a non-remote window) and then use a command to open a remote folder URI. At least it did... I haven’t tried it in a couple months, since the resolver part has been stable.

**Comment by dilin-MS** [comment]
I met the same problem here. 

Before VS 1.39, it works well and when I run F5 to debug, the debug window will auto-open the `${workspaceRoot}/data/` folder for me to debug. 
After update VS to 1.39, VS fails to debug saying `Cannot debug extension (r.filter is not a function)`. Only by removing the ` ${workspaceRoot}/data/` in the `args` can debug mode works.

```json
// A launch configuration that compiles the extension and then opens it inside a new window
{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Extension",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": ["--extensionDevelopmentPath=${workspaceRoot}" , "${workspaceRoot}/data/"],
            "stopOnEntry": false,
            "sourceMaps": true,
            "outFiles": [ "${workspaceRoot}/out/src/**/*.js" ],
            "preLaunchTask": "npm: watch"
        },
        {
            "name": "Extension Tests",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "${workspaceRoot}/test/resources/project1/project.code-workspace",
                "--extensionDevelopmentPath=${workspaceRoot}", 
                "--extensionTestsPath=${workspaceRoot}/out/test" 
            ],
            "stopOnEntry": false,
            "sourceMaps": true,
            "outFiles": [ "${workspaceRoot}/out/test/**/*.js" ],
            "preLaunchTask": "npm: watch"
        }
    ]
}
```

**Comment by connor4312** [comment]
No longer appears to happen with the new debugger
