### ISSUE TITLE
error from the extension host: spawn /usr/share/code/code (deleted) ENOENT

### ISSUE THREAD

**Issue by antoniomquadrosfilho** [Microsoft/vscode#7866]
- VSCode Version: 1.1.1
- OS Version: Fedora 23
- Node 5.10
- Shell 0.37.6

Steps to Reproduce:

1. Update to version 1.2.1

Problem

1. I continued at version 1.1.1
2. The package spawn was broken
3. The code isn't colorized, how if vs code doesn't support php code

**Comment by dbaeumer** [comment]
Might be @alexandrudima

**Comment by Tyriar** [comment]
@antoniomquadrosfilho can you try install the rpm again via command line? I find sometimes it doesn't work when updating via the GUI at least.

**Comment by tadasdanielius** [comment]
I have the same issue on Linux Mint debian edition (LMDE 2 Betsy) and deb package
Tried to install with GUI and via command line, no luck.

messageService.ts:119Error from the extension host: spawn /usr/share/code/code (deleted) ENOENTe.doShow @ messageService.ts:119
ipc.cp.ts:156IPC "Watcher" errored with Error: spawn /usr/share/code/code (deleted) ENOENT
ipc.cp.ts:156IPC "Git" errored with Error: spawn /usr/share/code/code (deleted) ENOENT

Now getting same problem on 1.2.0 after uninstalling 1.2.1 and reinstalling 1.2.0

**Comment by Tyriar** [comment]
@tadasdanielius can you see if this is happening using the Insiders build? https://code.visualstudio.com/insiders

**Comment by tadasdanielius** [comment]
Just tried code-insiders_1.3.0-1467004291_amd64.deb
Looks like it's working now. I don't see this error anymore.

**Comment by Tyriar** [comment]
Since 1.3.0 is shipping in a couple of weeks and it seems fine there I'll resolve this. It's potentially caused by https://github.com/Microsoft/vscode/pull/7350

**Comment by pragmascript** [comment]
I have the same issue with released 1.3.0 on mint

**Comment by komasoftware** [comment]
still seeing this on 1.14.0 on Ubuntu 

Error from the extension host: spawn /usr/share/code/code (deleted) 

How can we see the full error ?

**Comment by Tyriar** [comment]
@komasoftware this might happen when you update VS Code without closing down all windows (ctrl+q) and relaunching.

**Comment by ztrange** [comment]
I had the problem and solved it doing: `sudo apt-get install --reinstall code`

**Comment by mirabalj** [comment]
I have the same problem in Elementary OS, with VS 1.17.1. Some fix? Thanks in advance.

**Comment by Tyriar** [comment]
This is a common issue on Linux when you upgrade and *do not* restart the application. The fix is to close all windows (ctrl+q) and relaunch VS Code whenever you see this.
