### ISSUE TITLE
Terminal opens slow

### ISSUE THREAD

**Issue by Profesor08** [microsoft/vscode#247047]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.100.0-insider (user setup)
Commit: 1b000ef82b3c3082833f6b04e050bc0e4e12ae3b
Date: 2025-04-18T05:31:28.011Z
Electron: 34.5.1
ElectronBuildId: 11369351
Chromium: 132.0.6834.210
Node.js: 20.19.0
V8: 13.2.152.41-electron.0
OS: Windows_NT x64 10.0.26100

Steps to Reproduce:

This is same issue as https://github.com/microsoft/vscode/issues/241694

1. Start VSCode
2. Open Terminal, open anoter, they opens slow

bisect:

```
git bisect start && git bisect bad f23861839fb21c44102dac215998647b4cd02840 && git bisect good 105d4af21c11ed9f13e65feba4ce4b41217e2024
```

**Comment by meganrogge** [comment]
@Profesor08 could you pls bisect this to find the bad commit?

**Comment by meganrogge** [comment]
that's the output of vscode bisect. that command needs to be run to identify the first bad commit.

**Comment by Profesor08** [comment]
> that's the output of vscode bisect. that command needs to be run to identify the first bad commit.

```bash
git bisect start && git bisect bad f23861839fb21c44102dac215998647b4cd02840 && git bisect good 105d4af21c11ed9f13e65feba4ce4b41217e2024
Bisecting: 51 revisions left to test after this (roughly 6 steps)
[a87baa41605c7447d710ea5b46a12074335bbb8a] Merge pull request #210271 from pouyakary/pouya/custom-section-header-marks
```

**Comment by Profesor08** [comment]
Tried to compile and run code localy, but I get error when open terminal. Something required is missing. Also checked and there is no such files. I think now I'm not much helpfull.

![Image](https://github.com/user-attachments/assets/e5903bea-d37f-4593-bdbc-66c337b592c8)

```bash
The terminal process failed to launch: A native exception occurred during launch (Cannot find module '../build/Release/conpty.node'
Require stack:
- d:\git\@prof-contribute\vscode\node_modules\node-pty\lib\windowsPtyAgent.js
- d:\git\@prof-contribute\vscode\node_modules\node-pty\lib\windowsTerminal.js
- d:\git\@prof-contribute\vscode\node_modules\node-pty\lib\index.js).
```

**Comment by Profesor08** [comment]
After a few updated, the issue is no longer reproducing.
