### ISSUE TITLE
After updating vscode started showing multiple definitions

### ISSUE THREAD

**Issue by denismamorim** [Microsoft/vscode#51489]
Hello

After updating from version 1.23.1 to 1.24.0 the shortcut "Go to definition" started finding two definitions where there is only one. A simple way yo reproduce is this:

```js
const f  = x => console.log(x)
f()
```

When I Ctrl + Click or F12 the f function it finds two definitions:
![image](https://user-images.githubusercontent.com/5399516/41181245-775f8f8e-6b47-11e8-82ec-57d00af56e21.png)

Is there any way to revert to the previews behavior?

I am using vscode v1.24.0 in Ubuntu 16.04

Thanks in advance

**Comment by geirsagberg** [comment]
I noticed this as well. This seems to me to be a bug; there is only one real definition here, as is evidenced by clicking results showing the same line.

**Comment by alexjeffburke** [comment]
Thanks for opening this issue, I thought I was going nuts - I think what I'm experiencing is related: it looks like vscode gets confused between the call-site of a function expression and the definition of it earlier in the file, so while it jumps up to the definition it also opens up the multiple definitions pane. The effect is that every other cmd-click needs to be followed by pressing escape. Just confirmed on second machine this came in on upgrade for 1.23.1 -> 1.24.0. Thanks.

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/24861 to track this upstream

**Comment by benevbright** [comment]
any workaround?
