### ISSUE TITLE
VSCode shows unexpected problem on valid ts codes after v1.68.1

### ISSUE THREAD

**Issue by whzx5byb** [microsoft/vscode#157134]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1 
- OS Version: Windows_NT x64

Steps to Reproduce:

1. Create a new file, select the language as Typescript.
2. Type in the code below:
```ts
class A {
    static Foo = class {}
}

class B extends A.Foo {}
```

This is valid typescript, and it works OK in v1.67.2 and prior versions.
However, in v1.68.1(also in the latest version), the editor shows two unexpected problems: 
`Cannot find name 'A'.ts(2304)`
`'A' only refers to a type, but is being used as a namespace here.ts(2702)`

Screenshots for comparison:
1.67.2
![1](https://user-images.githubusercontent.com/6128692/182934564-90b465eb-b59d-4555-af8f-dd53031c829f.png)

1.68.1
![2](https://user-images.githubusercontent.com/6128692/182934576-7f4e64ff-3d09-4538-b364-6b573684bf9f.png)

Notice that this code works OK in [Typescript Playground v4.7.3](https://www.typescriptlang.org/play?ts=4.7.3#code/MYGwhgzhAECC0G8CwAoa7oQC5iwS2GgDEB7E6AXmlEhgQF9VGVUapoAhaAUwA8tuAOwAmMWADpS5BkA) (which is bundled by VSCode v1.68.1).

**Comment by VSCodeTriageBot** [comment]
Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.70.0. Please try upgrading to the latest version and checking whether this issue remains.

Happy Coding!
