### ISSUE TITLE
File links in intergrated terminal no longer respect line numbers, if the path is preceded by `>`

### ISSUE THREAD

**Issue by adalisk-emikhaylov** [microsoft/vscode#177192]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.0 (and 1.76.1)
- OS Version: Windows_NT x64 10.0.19045

Clicking a file path in the terminal, followed by a line number, no longer scrolls to the specified line. This only happens if the path is preceded by `>`.

This is a regression, it used to work in recent versions (1.75.x I believe).

Steps to Reproduce:

1. In integrated terminal: `echo '1>C:\path\to\some\file.cpp(3,1): error C2059: syntax error: ...'` (use a path to existing non-empty file)
2. Alt+click the path
3. The file is opened, but not at the specified line number (3 in this case)

This only happens if the path is preceded by `>`. Since MSVC C++ compiler outputs paths in this format, this is a common use case.

This seems to affect all line number formats: `(row,col):`, `(row):`, `:row:col:`, `:row:`.

**Comment by VSCodeTriageBot** [comment]
Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.76.1. Please try upgrading to the latest version and checking whether this issue remains.

Happy Coding!
