### ISSUE TITLE
Problems disappear

### ISSUE THREAD

**Issue by martinog2** [Microsoft/vscode#73153]
After updating to 1.33.1 I'm seeing a bug where problems disappear.

VS Code version 1.33.1
OS: Windows 10.

Repro steps:
1. Open vs code
2. Explorer -> Open folder.
3. Create folder 'TestVSCodeBug' and select it.
4. File -> New File.
5. Enter the following:
	//@ts-check
	let x=1;
	y=2;
6. File -> Save As -> test1.js
7. Click test1.js in Explorer. As expected the 'y=2' line shows as error. Red in Explorer, and an entry in Problems view: 'Cannot find name 'y'.
8. File -> New File.
9. Enter the following:
	//@ts-check
	let z=3;
10. File -> Save As -> test2.js
11. Close both files.
12. Click test1.js in Explorer. Problem appears as expected.
13. Click test2.js in Explorer.

Expected results:
Problem in test1.js remains visible, by showing in Explorer as red, and by showing entry in Problems view.

Actual results:
The problem in test1.js disappear in both Explorer and Problems view.

Guess I'm reverting back to 1.30.2, again. (1.32.3 broke terminal name feature which I regularly use, and 1.33.1 has this even worse bug of Problems disappearing....)

**Comment by mjbvz** [comment]
In steps 12 and 13, you are likely opening the files in [preview mode](https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode). This means that when you open `test2`, `test1` is closed (and therefore its errors are no longer shown).

We only show errors for files that are open. #13953 tracks always showing errors
