### ISSUE TITLE
Extension host is unresponsive.

### ISSUE THREAD

**Issue by kanren3** [microsoft/vscode#321901]
Version: 1.125.0 (system setup)
Commit: 93cfdd489c3b228840d0f86ec77c3636277c93ea
Date: 2026-06-15T22:24:03Z
Electron: 42.2.0
ElectronBuildId: 14159160
Chromium: 148.0.7778.97
Node.js: 24.15.0
V8: 14.8.178.14-electron.0
OS: Windows_NT x64 10.0.19044

---

When I launch VS Code, the DevTools console first shows:

```
INFO Extension host (LocalProcess pid: 9768) is unresponsive.
```

Then, after a delay ranging from about 10–20 seconds to several minutes, it finally shows:

```
INFO Extension host (LocalProcess pid: 9768) is responsive.
```

During this entire period, both the **Search** and **Git** features are completely unusable (they do not respond or show any results). Other editor functionality may also be affected, but these two are the most noticeable.

**Expected behavior:** The extension host should become responsive quickly after startup, and Search/Git should be available without significant delay.

**Actual behavior:** The extension host stays unresponsive for a highly variable length of time (from seconds to minutes), during which Search and Git are blocked.

**Comment by lppedd** [comment]
Can confirm that 1.125.0 is broken.
- Extension activation is slow up to minutes
- Git content doesn't load
- Development extension host is unresponsive

**Comment by ashkan-ahmadi** [comment]
Having the same issue. The Source Control panel does nothing and the whole app is slow now. My info:

```
Version: 1.125.0 (Universal)
Commit: 93cfdd489c3b228840d0f86ec77c3636277c93ea
Date: 2026-06-15T22:24:03Z
Electron: 42.2.0
ElectronBuildId: 14159160
Chromium: 148.0.7778.97
Node.js: 24.15.0
V8: 14.8.178.14-electron.0
OS: Darwin arm64 25.5.0
```

**Comment by jruales** [comment]
Those who have 100% repro, could you please provide more info about if this happens in all folders, what extensions you have installed, etc.? Logs would also be helpful, as they might show what is going on, have an exit code, etc.

**Comment by lppedd** [comment]
Unfortunately I had to rollback immediately because I had work to complete. I'll give it a go once again soon I hope, or maybe I'll just wait for 1.126.0.

**Comment by jruales** [comment]
I'm part of VS Code team, and we're trying to collect information about the issue so that we can fix it for 1.126.0, so any information, logs, crash dumps, etc. would be useful to understand the issue, since we are not able to reproduce the issue on our side

**Comment by lppedd** [comment]
Yup I understand. Let me update again then, and I'll try to repro.

**Comment by lppedd** [comment]
@jruales reproduced. I'm trying to see whether I can find if a specific extension is the problem.  
For logs, is there a place you can reach where we can submit files with potentially sensitive info? I'd prefer that route.

**Comment by jruales** [comment]
@lppedd  I have emailed you to the address on your profile. You can share over there

**Comment by lppedd** [comment]
@jruales seen the email, thanks! However I've managed to reproduce with no extensions enabled and with no folder/workspace open, checked and I see nothing sensitive in this short log file.

The following DevTools log: [vscode-app-1781811210459.log](https://github.com/user-attachments/files/29109446/vscode-app-1781811210459.log)  
Contains this section:
```txt
log.ts:117  INFO Extension host (LocalProcess pid: 29400) is unresponsive.
log.ts:117  INFO Extension host (LocalProcess pid: 29400) is responsive.
log.ts:117   ERR Canceled: Canceled
    at SCe.value (async.ts:113:11)
    at _._deliver (event.ts:1364:13)
    at _._deliverQueue (event.ts:1375:9)
    at _.fire (event.ts:1399:9)
    at LCe.cancel (cancellation.ts:69:19)
    at $e.cancel (cancellation.ts:124:16)
    at Pge.triggerRefresh (chatModes.ts:218:1)
    at SCe.value (chatModes.ts:115:1)
    at _._deliver (event.ts:1364:13)
    at _.fire (event.ts:1395:9)
    at SCe.value (customizationHarnessService.ts:620:1)
    at _._deliver (event.ts:1364:13)
    at _._deliverQueue (event.ts:1375:9)
    at _.fire (event.ts:1399:9)
    at promptsServiceImpl.ts:1407:1
    at async.ts:419:13 Failed to load custom agents
```

Between unresponsive and responsive there are about 30 seconds.

**Comment by lppedd** [comment]
Another DevTools log, with another error from Copilot.

[vscode-app-1781811919931.log](https://github.com/user-attachments/files/29109692/vscode-app-1781811919931.log)

**Comment by jruales** [comment]
@lppedd  Thanks a lot! We'll take a look now

**Comment by lppedd** [comment]
Setting
```text
"chat.disableAIFeatures": true
```
Does the trick. No more unresponsiveness. So it is Copilot most probably.

**Comment by dmitrivMS** [comment]
@lppedd Thanks a lot for the info!

**Comment by alexdima** [comment]
@lppedd Does this reproduce with a fresh user profile i.e. `code --user-data-dir C:\some\new\folder`? (you've got to close all windows first)

**Comment by lppedd** [comment]
@alexdima looks like it does not!

**Comment by alexdima** [comment]
🤔 This is tricky! :) We could try two directions to narrow this down, one more technical and one less technical:

---

1. (the more technical) Attach to the extension host process to see where execution is stuck or capture a CPU profile. Close all windows, launch Code normally, run `F1` > `Developer: Debug Extension Host in Dev Tools`, Go to `Performance tab` > `Capture profile` for the unresponsive period or if it's just stuck go to the Sources tab and press the Pause button to see where execution is stuck:

> <img width="1162" height="454" alt="Image" src="https://github.com/user-attachments/assets/1fd1d583-ceaa-4e39-85ce-0790fcdf46b0" />

---

2. (the less technical) Does it reproduce in a fresh profile in your regular user data dir? Close all windows, launch Code normally, then create a new profile (Gear > Profiles > New Profile > leave everything as is > Create) then switch the window to the new profile (Gear > Profile > Untitled 1) or whatever name you gave it. If it doesn't reproduce, slowly enable inheriting Settings, Extensions, etc. from the Default profile until it starts reproducing.

> <img width="900" height="597" alt="Image" src="https://github.com/user-attachments/assets/aea33b59-c78e-41f3-942a-2edd811a9f1d" />

---

Please LMK which one you chose and thank you for support in tracking this down!

**Comment by lppedd** [comment]
@alexdima I went route 1.

- Performance view is always completely empty, so I can't take CPU snapshots.
- Pausing execution through the Sources views:
  - Is "stuck" until the extension host is responsive again.
  - The following is what I see when execution is resumed:
    
    <img width="1755" height="933" alt="Image" src="https://github.com/user-attachments/assets/a36386eb-8352-4c11-9b7d-ac837b740546" />

**Comment by deepak1556** [comment]
@lppedd thanks for trying the above steps, could you try this alternatively for the cpu profile. Run `Developer: Start Tracing` before the unresponsive and run `Developer: Stop Tracing` once the extension host is responsive, you can attach the generated profile to this issue thread or share it at vscode-logs@microsoft.com

**Comment by lppedd** [comment]
@deepak1556 hopefully I've let it record long enough to capture something useful. Let me know in case I need to redo it.

[code-s7GVQi4p.trace.txt](https://github.com/user-attachments/files/29111638/code-s7GVQi4p.trace.txt)

**Comment by deepak1556** [comment]
Thank you, yes it seems to contain the relevant stack, was it pid 20316 that was unresponsive ?

**Comment by lppedd** [comment]
@deepak1556 yup.
```txt
INFO Extension host (LocalProcess pid: 20316) is unresponsive.
INFO Extension host (LocalProcess pid: 20316) is responsive.
```

**Comment by AdamWr** [comment]
I have similar problem mentioned in https://github.com/microsoft/vscode/issues/318730#issuecomment-4685708452 and https://github.com/microsoft/vscode/issues/318730#issuecomment-4732654419

In my case it seems to happen even with all extensions disabled and in a new profile when I open just a new VS Code window (though the delay in the new profile is smaller).
It works fine when I disable `AI features` or when I remove `state.vscdb` file from `\Code - Insiders\User\globalStorage`, but only until I log in to GitHub Copilot again.
It happens on host (Windows 11), but interesting thing is that I don't see that problem in WSL (`Networking mode` set to `NAT`).
For what it's worth, GitHub Copilot Chat logs in WSL (where it works fine):
<details><summary>Logs</summary>

```
2026-06-18 22:12:19.450 [info] Copilot Chat: 0.54.2026061802, VS Code: 1.126.0-insider
2026-06-18 22:12:19.487 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:12:19.487 [info] ConversationFeature: Activating contributions
2026-06-18 22:12:19.490 [info] Registering default platform agent...
2026-06-18 22:12:19.491 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:12:19.491 [info] [code-referencing] Public code references are enabled.
2026-06-18 22:12:19.491 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:12:19.491 [info] [code-referencing] Public code references are enabled.
2026-06-18 22:12:19.491 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:12:19.491 [info] [code-referencing] Public code references are enabled.
2026-06-18 22:12:19.492 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:12:19.492 [info] [code-referencing] Public code references are enabled.
2026-06-18 22:12:19.493 [info] activationBlocker from 'conversationFeature' took for 2026ms
2026-06-18 22:12:19.494 [info] [context keys] Setting context key: github.copilot-chat.activated
2026-06-18 22:12:19.494 [info] AuthenticationService: firing onDidAuthenticationChange from handleAuthChangeEvent identity change. Has token: true
2026-06-18 22:12:19.494 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:12:19.500 [info] GithubAvailableEmbeddingTypesManager: Got embeddings. Primary: metis-1024-I16-Binary. Deprecated:
2026-06-18 22:12:19.502 [info] Successfully activated the GitHub.vscode-pull-request-github extension.
2026-06-18 22:12:19.502 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2026-06-18 22:12:19.502 [info] Successfully registered GitHub PR title and description provider.
2026-06-18 22:12:19.502 [info] Successfully registered GitHub PR reviewer comments provider.
2026-06-18 22:12:19.503 [info] WorkspaceChunkSearchService: using embedding type metis-1024-I16-Binary
2026-06-18 22:12:19.642 [info] [CopilotCLIChatSessionContentProvider] listSessions took 107.67979100000002ms
2026-06-18 22:12:19.662 [info] [CopilotCLIChatSessionContentProvider] listSessions took 1.6246320000000196ms
2026-06-18 22:12:20.121 [info] Fetched model metadata in 2644ms
```

</details>

New profile (small delay):
<details><summary>Logs</summary>

```
2026-06-18 22:12:58.571 [info] Copilot Chat: 0.54.2026061802, VS Code: 1.126.0-insider
2026-06-18 22:12:58.603 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:12:58.603 [info] ConversationFeature: Activating contributions
2026-06-18 22:12:58.603 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2026-06-18 22:12:58.612 [info] Registering default platform agent...
2026-06-18 22:12:58.615 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:12:58.615 [info] [code-referencing] Public code references are enabled.
2026-06-18 22:12:58.615 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:12:58.615 [info] [code-referencing] Public code references are enabled.
2026-06-18 22:12:58.615 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:12:58.615 [info] [code-referencing] Public code references are enabled.
2026-06-18 22:12:58.615 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:12:58.615 [info] [code-referencing] Public code references are enabled.
2026-06-18 22:12:58.615 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:12:58.615 [info] [code-referencing] Public code references are enabled.
2026-06-18 22:12:58.616 [info] activationBlocker from 'conversationFeature' took for 5296ms
2026-06-18 22:12:58.616 [info] AuthenticationService: firing onDidAuthenticationChange from handleAuthChangeEvent identity change. Has token: true
2026-06-18 22:12:58.616 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:12:58.618 [info] BYOK: registered 9 provider(s): ollama, anthropic, gemini, xai, openai, openrouter, azure, customoai, customendpoint
2026-06-18 22:12:58.618 [info] BYOK: fetching known models list
2026-06-18 22:12:58.618 [info] [context keys] Setting context key: github.copilot-chat.activated
2026-06-18 22:12:58.626 [info] activationBlocker from 'languageModelAccess' took for 5305ms
2026-06-18 22:12:58.637 [info] [CopilotCLIChatSessionContentProvider] listSessions took 1.316000000000713ms
2026-06-18 22:12:58.643 [info] [CopilotCLIChatSessionContentProvider] listSessions took 0.18289999999979045ms
2026-06-18 22:12:58.648 [info] [CopilotCLI] MCP server started. Lock file: C:\Users\Adam\.copilot\ide\88552f4c-cb37-49a8-9cce-a0696ccfbe0c.lock
2026-06-18 22:12:58.648 [info] [CopilotCLI] Server URI: pipe:%5C%5C.%5Cpipe%5Cmcp-ade6d535-f354-499e-80c7-6023b9f203c8.sock#%2Fmcp
2026-06-18 22:12:58.839 [info] Fetched model metadata in 5513ms
```

</details>

My main profile with Git repository (the slowest one):
<details><summary>Logs</summary>

```
2026-06-18 22:13:25.628 [info] Copilot Chat: 0.54.2026061802, VS Code: 1.126.0-insider
2026-06-18 22:13:25.662 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:13:25.662 [info] ConversationFeature: Activating contributions
2026-06-18 22:13:25.664 [info] Registering default platform agent...
2026-06-18 22:13:25.665 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:13:25.666 [info] [code-referencing] Public code references are enabled.
2026-06-18 22:13:25.666 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:13:25.666 [info] [code-referencing] Public code references are enabled.
2026-06-18 22:13:25.666 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:13:25.666 [info] [code-referencing] Public code references are enabled.
2026-06-18 22:13:25.666 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:13:25.667 [info] [code-referencing] Public code references are enabled.
2026-06-18 22:13:25.668 [info] activationBlocker from 'conversationFeature' took for 10402ms
2026-06-18 22:13:25.670 [info] [context keys] Setting context key: github.copilot-chat.activated
2026-06-18 22:13:25.671 [info] AuthenticationService: firing onDidAuthenticationChange from handleAuthChangeEvent identity change. Has token: true
2026-06-18 22:13:25.671 [info] copilot token sku: copilot_enterprise_seat_quota
2026-06-18 22:13:25.678 [info] GithubAvailableEmbeddingTypesManager: Got embeddings. Primary: metis-1024-I16-Binary. Deprecated:
2026-06-18 22:13:25.679 [info] Successfully activated the GitHub.vscode-pull-request-github extension.
2026-06-18 22:13:25.679 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2026-06-18 22:13:25.679 [info] Successfully registered GitHub PR title and description provider.
2026-06-18 22:13:25.679 [info] Successfully registered GitHub PR reviewer comments provider.
2026-06-18 22:13:25.679 [info] WorkspaceChunkSearchService: using embedding type metis-1024-I16-Binary
2026-06-18 22:13:25.894 [info] Fetched model metadata in 10621ms
```

</details>

There is `activationBlocker from 'conversationFeature' took for 10402ms` and `Fetched model metadata in 10621ms`, I see similar delay in Git logs, so I'm not sure if it's a culprit or just an effect of the issue.

I sent logs to mentioned email.

```
22:50:01.756 log.ts:117  INFO Extension host (LocalProcess pid: 23736) is unresponsive.
22:50:07.329 log.ts:117  INFO Extension host (LocalProcess pid: 23736) is responsive.
```

**Comment by deepak1556** [comment]
Thanks for the profiles, it was super helpful. We are preparing a fix at https://github.com/microsoft/vscode/pull/321998, we will update here again with new builds once ready.

@AdamWr the freeze stack in your case matches the one from @lppedd so we are confident with the nature of issue.

**Comment by jruales** [comment]
@lppedd @AdamWr or anyone else running into this issue, could you all please try installing this VSIX VS Code extension with the fix to check if it fixes the issue for you?
https://drive.google.com/file/d/16E7BT_ImjVf0H3XCreQwvx8p6OYkNBWM/view?usp=sharing

**Comment by lppedd** [comment]
@jruales it fixes the issue but I see the following in the DevTools console:
```txt
ERR process.report?.getReport is not a function: TypeError: process.report?.getReport is not a function
ERR [ChatSessionsService] Failed to resolve sessions for provider copilotcli TypeError: process.report?.getReport is not a function
```

**Comment by AdamWr** [comment]
After installing the extension, the delay issue is fixed. Thank you :)
By the way, I see the same errors in console:
```
ERR process.report?.getReport is not a function: TypeError: process.report?.getReport is not a function
	at ggt (file:///c:/Users/Adam/.vscode/extensions/github.copilot-chat-0.53.1/node_modules/@github/copilot/sdk/index.js:53:168891)
	at i1r (file:///c:/Users/Adam/.vscode/extensions/github.copilot-chat-0.53.1/node_modules/@github/copilot/sdk/index.js:53:168521)
	at Zae (file:///c:/Users/Adam/.vscode/extensions/github.copilot-chat-0.53.1/node_modules/@github/copilot/sdk/index.js:53:168957)
	at bgt (file:///c:/Users/Adam/.vscode/extensions/github.copilot-chat-0.53.1/node_modules/@github/copilot/sdk/index.js:55:583)
	at KU (file:///c:/Users/Adam/.vscode/extensions/github.copilot-chat-0.53.1/node_modules/@github/copilot/sdk/index.js:55:773)
	at Object.get (file:///c:/Users/Adam/.vscode/extensions/github.copilot-chat-0.53.1/node_modules/@github/copilot/sdk/index.js:55:857)
	at JOr (file:///c:/Users/Adam/.vscode/extensions/github.copilot-chat-0.53.1/node_modules/@github/copilot/sdk/index.js:5701:52820)
	at <instance_members_initializer> (file:///c:/Users/Adam/.vscode/extensions/github.copilot-chat-0.53.1/node_modules/@github/copilot/sdk/index.js:5701:70058)
	at new N0e (file:///c:/Users/Adam/.vscode/extensions/github.copilot-chat-0.53.1/node_modules/@github/copilot/sdk/index.js:5701:70102)
	at new t (file:///c:/Users/Adam/.vscode/extensions/github.copilot-chat-0.53.1/node_modules/@github/copilot/sdk/index.js:5702:4614)
	at gi.executor (c:\Users\Adam\.vscode\extensions\github.copilot-chat-0.53.1\dist\extension.js:3002:14751)
	at async jV._getAllSessions (c:\Users\Adam\.vscode\extensions\github.copilot-chat-0.53.1\dist\extension.js:3002:19311)
	at async y (c:\Users\Adam\.vscode\extensions\github.copilot-chat-0.53.1\dist\extension.js:3036:1096)
	at async c:\Users\Adam\.vscode\extensions\github.copilot-chat-0.53.1\dist\extension.js:3036:1551
	at async Object.refreshHandler (file:///c:/Users/Adam/AppData/Local/Programs/Microsoft%20VS%20Code/93cfdd489c/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:562:36491)
	at async wf.$refreshChatSessionItems (file:///c:/Users/Adam/AppData/Local/Programs/Microsoft%20VS%20Code/93cfdd489c/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:562:47363)
ERR [ChatSessionsService] Failed to resolve sessions for provider copilotcli TypeError: process.report?.getReport is not a function
```

**Comment by alexdima** [comment]
Thank you @AdamWr @lppedd ❤️ . We also found the initial patch was not good, #322038 patches the patch 😅 . We are working on the 1.125.1 release. Will post here a link to the build as soon as we have it in case you would be willing to please verify that the freeze is addressed in a full vscode build.

For anyone curious, thanks to your help, we believe we have found the root cause that on some machines `process.report.getReport()` is causing freezes and the Copilot SDK was probing that to determine the current OS in a very precise manner. Our current hotfix is to patch this function away (it is not guaranteed to be there in all nodejs environments) and we will also change the Copilot SDK to avoid using it in the future. The challenge is that this does not reproduce on our side, it seems to only cause freezes on certain machines.

**Comment by hardisatria404-ship-it** [comment]
oky

**Comment by alexdima** [comment]
:wave: We have a build ready to roll out:

VS Code Build: fcf604774b9f2674b473065736ee75077e256353 , here are download links for macOS and windows. Could I kindly ask you @AdamWr @lppedd to please download an install this build and check that the issue is resolved


- [darwin](https://vscode.download.prss.microsoft.com/dbazure/download/stable/fcf604774b9f2674b473065736ee75077e256353/VSCode-darwin.zip)
- [darwin-arm64](https://vscode.download.prss.microsoft.com/dbazure/download/stable/fcf604774b9f2674b473065736ee75077e256353/VSCode-darwin-arm64.zip)
- [darwin-arm64-dmg](https://vscode.download.prss.microsoft.com/dbazure/download/stable/fcf604774b9f2674b473065736ee75077e256353/VSCode-darwin-arm64.dmg)
- [darwin-universal](https://vscode.download.prss.microsoft.com/dbazure/download/stable/fcf604774b9f2674b473065736ee75077e256353/VSCode-darwin-universal.zip)
- [darwin-universal-dmg](https://vscode.download.prss.microsoft.com/dbazure/download/stable/fcf604774b9f2674b473065736ee75077e256353/VSCode-darwin-universal.dmg)
- [darwin-x64-dmg](https://vscode.download.prss.microsoft.com/dbazure/download/stable/fcf604774b9f2674b473065736ee75077e256353/VSCode-darwin-x64.dmg)
- [win32-arm64](https://vscode.download.prss.microsoft.com/dbazure/download/stable/fcf604774b9f2674b473065736ee75077e256353/VSCodeSetup-arm64-1.125.1.exe)
- [win32-arm64-archive](https://vscode.download.prss.microsoft.com/dbazure/download/stable/fcf604774b9f2674b473065736ee75077e256353/VSCode-win32-arm64-1.125.1.zip)
- [win32-arm64-user](https://vscode.download.prss.microsoft.com/dbazure/download/stable/fcf604774b9f2674b473065736ee75077e256353/VSCodeUserSetup-arm64-1.125.1.exe)
- [win32-x64](https://vscode.download.prss.microsoft.com/dbazure/download/stable/fcf604774b9f2674b473065736ee75077e256353/VSCodeSetup-x64-1.125.1.exe)
- [win32-x64-archive](https://vscode.download.prss.microsoft.com/dbazure/download/stable/fcf604774b9f2674b473065736ee75077e256353/VSCode-win32-x64-1.125.1.zip)
- [win32-x64-user](https://vscode.download.prss.microsoft.com/dbazure/download/stable/fcf604774b9f2674b473065736ee75077e256353/VSCodeUserSetup-x64-1.125.1.exe)

**Comment by lppedd** [comment]
@alexdima thank you! Should we first uninstall the patched Copilot extension?

Edit: nevermind, there doesn't seem to be a way to do it through the Extensions tool window.

**Comment by lppedd** [comment]
I see

```
WARN Skipping extension /c:/Users/edoardo.luppi/.vscode/extensions/github.copilot-chat-0.53.1 in favour of the builtin extension /c:/Users/edoardo.luppi/AppData/Local/Programs/Microsoft VS Code/fcf604774b/resources/app/extensions/copilot.
```

Can I just remove the extension v0.53.1 manually?

This is also interesting. 1.125.0 isn't taken into account. I just got automatically rolled back to 1.124.2 ahaha

<img width="548" height="311" alt="Image" src="https://github.com/user-attachments/assets/cd494882-c9e4-4dcf-a8e5-398751a67546" />

**Comment by lppedd** [comment]
Ok, it seems to have fixed the problem! For posterity, this is what I did to have a clean situation:

1. `code --uninstall-extension github.copilot-chat --force` to remove the patched Copilot extension
2. `"update.mode": "none"` to avoid updates that roll back the version
3. Install latest VS Code

**Comment by AdamWr** [comment]
I tested in virtual machine and delay is fixed :)

<details><summary>Video (left current stable build, right test build)</summary>

https://github.com/user-attachments/assets/b048210c-573c-41ba-8f44-d6399529aec4

</details>

**Comment by alexdima** [comment]
Thank you very much! ❤️

**Comment by spartanatreyu** [comment]
This issue probably would have had a smaller blast radius if this was released: https://github.com/microsoft/vscode/issues/308615
