### ISSUE TITLE
SourceControlInputBox.visible is only in vscode.proposed.d.ts

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#90499]
@joaomoreno my SCM extension has no use for the input box, so after creating its instance using scm.createSourceControl I want to set .inputBox.visible=false

But visible is only defined in vscode.proposed.d.ts so I get this error reported when I save my change:

`Property 'visible' does not exist on type 'SourceControlInputBox'.`

It seems the property first got introduced by https://github.com/microsoft/vscode/pull/60051 but that caused a problem and had to be reverted on 24-Oct-2018 by https://github.com/microsoft/vscode/commit/fb1ed7927103006a8be8c42ea470126799b40ee6, which in turn was reverted later the same day by https://github.com/microsoft/vscode/commit/63da98253cf1c89e1e5e1691667072c8adf6a158

It passed testing on 30-Oct-2018 under #62068

More recently (4-Oct-2019) https://github.com/microsoft/vscode/pull/81982 (still open) has made use of the visible property despite still only being proposed. Perhaps it can do this because it's the built-in Git SCM rather than an extension.

Can this API be finalized soon?

**Comment by joaomoreno** [comment]
Yeah let's try to move it along.

**Comment by joaomoreno** [comment]
Sorry, @gjsjohnmurray, but had to push this forward to March. Will get it done as soon as the milestone starts.

**Comment by gjsjohnmurray** [comment]
No worries @joaomoreno, and thanks for the update.

**Comment by joaomoreno** [comment]
Ufff... I forgot I'll be out in March (paternity leave!) so have to push to April, sorry about that!

**Comment by gjsjohnmurray** [comment]
@joaomoreno no worries. I hope your own personal March endgame goes really well 👶
