### ISSUE TITLE
NSIS building is no longer working in 1.9.1

### ISSUE THREAD

**Issue by ElSenorEd** [Microsoft/vscode#20442]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|nsis|idleberg|2.7.1|
|nsis-plugins|idleberg|1.0.5|
|svg-icons|idleberg|0.2.2|
|vscode-nsis|KrystofRiha|0.0.1|

---

Steps to Reproduce:
1. Load NSIS file.  Hit Ctrl+B+Shift.  (nothing happens)
      - PATH system variable is correct.  C:\Program Files (x86)\NSIS.
      - settings.json appear correct.

Additionally, I rolled back to version 1.7.2 and NSIS building works.

Console log:
[Extension Host] WARNING: Promise with no error callback:8
shell.ts:437 Cannot read property 'trim' of undefined: TypeError: Cannot read property 'trim' of undefined
    at C:\Users\Ed\.vscode\extensions\idleberg.nsis-2.7.1\lib\makensis.js:25:51
    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:30381)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:1957)
    at _run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:3785)
    at _completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:3226)
    at e.resolveOk (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:8:17657)
    at d (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:8:16129)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ shell.ts:437(anonymous function) @ shell.ts:389e.onUnexpectedError @ errors.ts:68o @ errors.ts:88t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:282 [Extension Host] Object {exception: Object, error: null, promise: Object, id: 8}
extensionHost.ts:282 [Extension Host] TypeError: Cannot read property 'trim' of undefined
    at C:\Users\Ed\.vscode\extensions\idleberg.nsis-2.7.1\lib\makensis.js:25:51
    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:30381)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:1957)
    at _run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:3785)
    at _completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:3226)
    at e.resolveOk (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:8:17657)
    at d (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:8:16129)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by joaomoreno** [comment]
Duplicate of idleberg/vscode-nsis#5
