### ISSUE TITLE
`/build/` folder no longer compiles

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#141653]
```
yarn --cwd build compile
```

```
node_modules/@typescript-eslint/typescript-estree/dist/visitor-keys.d.ts:1:36 - error TS7016: Could not find a declaration file for module 'eslint-visitor-keys'. '/Users/alex/src/vscode/build/node_modules/eslint-visitor-keys/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/eslint-visitor-keys` if it exists or add a new declaration (.d.ts) file containing `declare module 'eslint-visitor-keys';`

1 import * as eslintVisitorKeys from 'eslint-visitor-keys';
                                     ~~~~~~~~~~~~~~~~~~~~~


Found 1 error in /Users/alex/src/vscode/build/node_modules/@typescript-eslint/typescript-estree/dist/visitor-keys.d.ts:1
```

I think it is caused by https://github.com/microsoft/vscode/commit/f30dba54302d2c00356e90604ec27aceeeb38bb5

(spotted via nightly monaco-editor publish task -- https://github.com/microsoft/monaco-editor/actions/workflows/publish.yml )

cc @joaomoreno we might want to improve vscode's CI to at least execute this in the hygiene check.

cc @hediet

**Comment by alexdima** [comment]
Thank you for the fast fix!
