### ISSUE TITLE
The Spiral extension on the marketplace is not activating on .spi and .spiproj files even though it works in the extension host

### ISSUE THREAD

**Issue by mrakgr** [microsoft/vscode#193129]
Version: 1.82.1 (user setup)
Commit: 6509174151d557a81c9d0b5f8a5a1e9274db5585
Date: 2023-09-08T08:45:05.575Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Install The Spiral Language 2.4.14.
2. Open .spi or a .spiproj file.
3. The extension isn't activating.
4. It works with 2.4.12.
5. What I am doing different between these two versions is having moved to ESBuild. The extension works in the Extension Host, but not when published.

**Comment by mrakgr** [comment]
I did a few more experiments, and it seems it only works if the `node_modules` folder is included even when the output is bundled. Load of good that does me.

**Comment by mrakgr** [comment]
```
Activating extension 'mrakgr.spiral-lang-vscode' failed: Cannot find module 'ws'
Require stack:
- c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\out\index.js
- c:\Users\Marko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\Marko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\Marko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
- .
```

This is what I get when I try to run the extension with the `node_modules` folder deleted. Why is ESBuild not bundling this into the `index.js` file?

**Comment by gjsjohnmurray** [comment]
Seems to have been explained in https://github.com/evanw/esbuild/issues/3386#issuecomment-1720224250

**Comment by mrakgr** [comment]
Yeah, the `ws` package which SignalR uses having too many hacks is the culprit.
