### ISSUE TITLE
Notebook kernel preloads can no longer find requirejs

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#110503]
- VSCode Version: 1.52.0 insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Load a kernel preload with code like so:
```typescript
        const requirejsfunc = (window as any).requirejs;
        if (requirejsfunc === undefined) {
            reject('Requirejs is needed, please ensure it is loaded on the page.');
        } else {
            requirejsfunc(pkg, resolve, reject);
        }
```
2. It will fail to find the requirejs window member

This was working in 1.50.0. 

Does this issue occur when all extensions are disabled?: N/A as extension is required to reproduce

**Comment by rchiodo** [comment]
Looks like requirejs is now a global, however it is not a function anymore.

I get this if I use the global:

![image](https://user-images.githubusercontent.com/19672699/98978220-7f262000-24ce-11eb-92c6-d5a9e8fda9a7.png)
