### ISSUE TITLE
GitHub Copilot Agent Host fails to start on Windows 10 x64 — runtime.node DLL initialization error

### ISSUE THREAD

**Issue by IRD1964** [microsoft/vscode#333934]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.135.0
- OS Version: Windows 10x64 

<img width="456" height="411" alt="Image" src="https://github.com/user-attachments/assets/45fe59ca-6c47-43d8-97a8-582c60d4debe" />

Home, Version 22H2 (OS Build 19045.6466)

Steps to Reproduce:

1. Open the workspace in VS Code.
2. Make sure GitHub Copilot is authenticated.
3. Start a Copilot Agent session.
4. Observe the Agent Host startup failure.

## Environment

- GitHub Copilot Chat: 0.63.0
- Copilot account: Free Limited Copilot
- Workspace: D:\IVD_SOURCE_LIBRARY

## Summary

GitHub Copilot Chat works normally: authentication succeeds and the Chat interface is available.

However, when I start a Copilot Agent session, Agent Host fails during startup before it can execute any user task.

## Expected behavior

The Copilot Agent should start and be able to perform a simple read-only task in the workspace.

## Actual behavior

Agent Host fails to load the native Copilot SDK runtime.

The VS Code log reports:

[CopilotCLISession] Failed to load @GitHub/copilot/sdk:
Error: Native addon "runtime" not found for win32-x64.

The first attempted native binary reports:

"A dynamic link library (DLL) initialization routine failed."

The loader then reports that runtime.win32-x64-msvc.node cannot be found.

The relevant path is:

extensions/copilot/node_modules/@GitHub/copilot/sdk/prebuilds/win32-x64/runtime.node

Authentication and normal Copilot Chat functionality work correctly.

## Important diagnostic detail

The failure appears to occur specifically during Agent Host startup. The normal Copilot Chat functionality is not affected.

The generic VS Code bug-report instructions recommend reproducing issues with extensions disabled. This particular failure cannot be reproduced without Copilot because the failing Agent Host is part of the Copilot functionality itself.

## Questions

1. Is this a known Windows compatibility or native-runtime issue in Copilot Agent Host?
2. How can I identify the exact DLL or Windows dependency preventing runtime.node from initializing?
3. Is there a known dependency on a specific Windows build, MSVC runtime, CPU instruction set, or Windows API?
4. What diagnostic procedure should be performed before reinstalling VS Code and Copilot?

I can provide the complete VS Code logs and perform additional diagnostic tests if required.

**Comment by IRD1964** [comment]
## Relation to existing Agent Host issue

This issue appears related to #329713, but my system is running Windows 10 22H2 (OS Build 19045.6466), not the older Windows builds identified in that issue.

Therefore, I would like to clarify whether the same native runtime problem can also affect supported Windows 10 22H2 systems.

In my case the first native load error is:

"A dynamic link library (DLL) initialization routine failed."

The subsequent "Cannot find module" message appears to be a fallback error.

**Comment by IRD1964** [comment]
Update (September 8, 2026)

Additional diagnostics after updating VS Code to 1.136.1:

- Windows 10 x64
- VS Code 1.136.1
- GitHub Copilot Agent still fails to start
- Microsoft Visual C++ 2015 Redistributable (x64) was updated to the current supported version
- The problem persists after the VC++ update
- Windows Event Viewer → Application shows:
  Event ID: 1000
  Source: Application Error
  Faulting application: Code.exe
  Faulting module: runtime.node
  Exception code: 0xc000001d (Illegal instruction)

The regular Copilot Chat works normally; only the Agent Host fails.

This appears to indicate that runtime.node is present but fails during native execution.

**Comment by IRD1964** [comment]
Additional finding:

I found a related GitHub Copilot CLI issue:
https://github.com/github/copilot-cli/issues/3310

That issue also involved a failure around the native `runtime` addon on Windows. In that case, the problem was caused by missing native prebuilds in a specific package version and was fixed in the next release.

My case is different because `runtime.node` is present, but Windows Event Viewer reports:

- Faulting application: Code.exe
- Faulting module: runtime.node
- Exception code: 0xc000001d (Illegal instruction)

However, this related issue suggests that the Agent Host failure may be worth investigating at the native runtime/package level, rather than treating it only as a local VS Code configuration problem.

The issue is reproducible on two Windows systems with different CPUs.
