### ISSUE TITLE
Broken build: Can't use `process` in `common`

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#49321]
First build that failed: https://vscode.visualstudio.com/VS%20Code/_build/index?buildId=120&_a=summary

Failures introduced by https://github.com/Microsoft/vscode/commit/8e162519519d9bd5e42b1cdccff7c9a771389522

```
2018-05-06T18:51:25.3451361Z ##[section]Starting: Run Monaco Editor Checks
2018-05-06T18:51:25.3456192Z ==============================================================================
2018-05-06T18:51:25.3456422Z Task         : PowerShell
2018-05-06T18:51:25.3456622Z Description  : This is an early preview. Run a PowerShell script on Windows, macOS, or Linux.
2018-05-06T18:51:25.3456835Z Version      : 2.129.0
2018-05-06T18:51:25.3457016Z Author       : Microsoft Corporation
2018-05-06T18:51:25.3457209Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
2018-05-06T18:51:25.3457442Z ==============================================================================
2018-05-06T18:51:26.2021537Z Generating script.
2018-05-06T18:51:26.2860747Z ##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\41d03609-7af2-4a3e-992b-d8d32e0b0e52.ps1'"
2018-05-06T18:51:26.9133413Z yarn run v1.3.2
2018-05-06T18:51:27.0149350Z $ tsc -p src/tsconfig.monaco.json --noEmit
2018-05-06T18:51:40.7328413Z src/vs/platform/files/common/files.ts(922,30): error TS2304: Cannot find name 'process'.
2018-05-06T18:51:40.7359299Z src/vs/platform/files/common/files.ts(923,30): error TS2304: Cannot find name 'process'.
2018-05-06T18:51:40.8110899Z error Command failed with exit code 1.
2018-05-06T18:51:40.8112312Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2018-05-06T18:51:41.1799816Z ##[error]PowerShell exited with code '1'.
2018-05-06T18:51:41.2919337Z ##[section]Finishing: Run Monaco Editor Checks
```
