### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by Anamalia-Christopher** [microsoft/vscode#100118]
Issue Type: <b>Bug</b>

I do not know what exatly I did wrong but vs code has been buggy of late. I updated it to a newer version (Version: 1.46.0) recently.None of my extensions work because of `Extension host terminated unexpectedly` error I keep getting on start up. I googled the error and the only solution was to delete the extentions causing it. I have deleted all the extensions i have and the problem still persists. 

when i 'Open Developer Tools', this is what i see from the console: 

```
dyld: Symbol not found: __ZN20wireless_diagnostics6google8protobuf2io16CodedInputStream24default_recursion_limit_E  

Referenced from: /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib  

Expected in: /usr/local/mysql/lib//libprotobuf-lite.dylib in /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib

from /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4515 
```

Please help me solve this. Thank you.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (0.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gregid** [comment]
Same problem here after upgrade to 1.46.0 - extension host terminates unexpectedly. 
This is the console output I got:
```
Extension Host
extensionHost.ts:223 FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
extensionHost.ts:222 Extension Host
extensionHost.ts:223  1: 00007FF77E42A69E uv_gettimeofday+11630286
 2: 00007FF77D8FFEC6 node::Abort+22
 3: 00007FF77D8FFF33 node::Abort+131
 4: 00007FF77B530738 v8::V8::GetVersion+792
 5: 00007FF77B5306DA v8::V8::GetVersion+698
 6: 00007FF77B574FD3 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> > >::_Make_iterator+59155
 7: 00007FF77B576584 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> > >::_Make_iterator+64708
 8: 00007FF77B57350B std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> > >::_Make_iterator+52299
 9: 00007FF77B5714BE std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> > >::_Make_iterator+44030
10: 00007FF77B57B9BC std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> > >::_Make_iterator+86268
11: 00007FF77B57BE2D std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> > >::_Make_iterator+87405
12: 00007FF77B74F822 v8::Unlocker::~Unlocker+52386
13: 00007FF77B99EEB0 v8::internal::TickSample::print+476192
14: 00007FF77BF4133D v8_inspector::V8ContextInfo::executionContextId+3229437
15: 000001DBC3F28C0C 
abstractExtensionService.ts:155 Extension host terminated unexpectedly. Code:  134  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:155
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
onDidChangeNotification @ notificationsAlerts.ts:40
8notificationsAlerts.ts:40 Canceled
onDidChangeNotification @ notificationsAlerts.ts:40
2commentService.ts:199 Canceled: Canceled
    at Object.t.canceled (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:46:952)
    at file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4194:278
    at Array.forEach (<anonymous>)
    at e.dispose (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4194:226)
    at e.dispose (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4206:826)
    at e._stopExtensionHostProcess (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4066:337)
    at e._onExtensionHostCrashed (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4067:117)
    at e._onExtensionHostCrashed (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4888:802)
    at e._onExtensionHostCrashOrExit (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4066:989)
    at file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4066:718
    at e.fire (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at t._onExtHostProcessExit (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4520:993)
    at ChildProcess.<anonymous> (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4516:123)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
commentService.ts:199 Canceled: Canceled
    at Object.t.canceled (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:46:952)
    at e._remoteCall (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4198:781)
    at Proxy.t.<computed>.i.charCodeAt.t.<computed> (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4195:365)
    at _.getDocumentComments (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6402:263)
    at file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3121:158
    at Map.forEach (<anonymous>)
    at e.getComments (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3121:137)
    at file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4478:720
    at Object.a [as createCancelablePromise] (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:125:257)
    at e.beginCompute (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4478:591)
    at e.onModelChanged (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4482:889)
    at file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4478:424
    at e.fire (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at e.setModel (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2283:596)
    at e.setInput (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5635:119)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async e.doSetInput (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4374:150)
    at async e.openEditor (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4372:756)
    at async file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6217:577
    at async e.openEditor (file:///C:/Users/Grzegorz.000/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6216:121)
```

**Comment by gregid** [comment]
Update: I fixed the problem with terminating extension host by:
1. disabling the `vscode-jest` extension
2. restarting vscode
3. enabling the `vscode-jest extension

**Comment by alexdima** [comment]
@Anamalia-Christopher Can you please try downloading VS Code Insiders from https://code.visualstudio.com/insiders/ , does that work correctly for you?

**Comment by Anamalia-Christopher** [comment]
I downloaded it. And it still didn’t work work for me. Same error message. ![Uploading 84767907...]()![Uploading 84767918...]()

**Comment by Anamalia-Christopher** [comment]
I downloaded it. And it still didn’t work work for me. Same error message.

**Comment by Anamalia-Christopher** [comment]
<img width="1136" alt="vscodeerror2" src="https://user-images.githubusercontent.com/31854543/84768633-18a2e180-afc4-11ea-8217-4df4edaea71a.png">
<img width="1136" alt="vscodeerror1" src="https://user-images.githubusercontent.com/31854543/84768670-28bac100-afc4-11ea-9574-162def47a50a.png">

**Comment by alexdima** [comment]
@Anamalia-Christopher Thank you for the extra information. I have never seen that stack before. 

We have support for creating a crash dump file if VS Code is launched with the `--crash-reporter-directory` command line option. Can you please follow the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports to create a crash dump? 

I think the `.dmp` file would be sufficient, as I think we could extract symbols from it. (i.e. I think you don't necessarily need to do all the steps)

**Comment by Anamalia-Christopher** [comment]
I followed the instructions in the link but I didn't get a `.dmp` file. Tried it serveral time but no `.dpm` file comes. I get a `.pma` file instead.

**Comment by Anamalia-Christopher** [comment]
<img width="549" alt="Screen Shot 2020-06-20 at 4 42 12 PM" src="https://user-images.githubusercontent.com/31854543/85206939-07840880-b315-11ea-8bc9-55023a023875.png">

**Comment by alexdima** [comment]
@Anamalia-Christopher Do you by any chance have `DYLD_LIBRARY_PATH` configured in your `~/.zshrc` ? https://github.com/microsoft/vscode/issues/100091#issuecomment-644388523 

@deepak1556 What else can we do here to find out what is the cause of the crash?

**Comment by Anamalia-Christopher** [comment]
I didn't but now I have `DYLD_LIBRARY_PATH` configured in my `~/.zshrc`. And it still isn't working for me.

**Comment by Anamalia-Christopher** [comment]
@alexdima, thank you so so much. I had `DYLD_LIBRARY_PATH` configured for my `.zprofile`. After commenting it out, it started working. Thank you so much.

**Comment by deepak1556** [comment]
@Anamalia-Christopher what was the `DYLD_LIBRARY_PATH` you had set ? Maybe the entitlement change is affecting this https://github.com/microsoft/vscode/pull/94728 , would be good to confirm. Thanks!

**Comment by Anamalia-Christopher** [comment]
`export DYLD_LIBRARY_PATH=/usr/local/mysql/lib/` was the path I had to comment out to make vs code work for me.

**Comment by deepak1556** [comment]
Do you have protobuf and mysql packages installed on your macOS ? If so what are their versions ?

**Comment by Anamalia-Christopher** [comment]
I use mysql version 8.0.19. I do not have protobuf package installed on my macOS.

**Comment by deepak1556** [comment]
what does `otool -L /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib` print ?

**Comment by deepak1556** [comment]
This is most likely https://github.com/Homebrew/homebrew-core/issues/45342 because of mysql shipping protobuf library.

Thanks @alexdima for narrowing down the cause. Just to re-iterate this is a package specific issue and not related to vscode.

**Comment by Anamalia-Christopher** [comment]
`otool -L /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib` prints 


`/System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib:
	/System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libprotobuf-lite.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/PrivateFrameworks/ProtocolBuffer.framework/Versions/A/ProtocolBuffer (compatibility version 1.0.0, current version 274.24.9)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1676.104.0)
	/System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libprotobuf.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libTelephonyUtilDynamic.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)`

**Comment by algorithmlover2016** [comment]
> `export DYLD_LIBRARY_PATH=/usr/local/mysql/lib/` was the path I had to comment out to make vs code work for me.

where did you find the command? 
It seems like mysql 8.0.19 lead to this problem. It set DYLD_LIBRARY_PATH=/usr/local/mysql/lib/. 
I have the same problem. but I can't find the set command

**Comment by lionchina** [comment]
Same problem here:

Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
