### ISSUE TITLE
Version 1.56 not working on Mac OS 10.10 Yosemite anymore

### ISSUE THREAD

**Issue by hiwilfried** [microsoft/vscode#125695]
VS Code [has been tested on OS X Yosemite](https://code.visualstudio.com/docs/supporting/requirements)? This might not be true for version 1.56.2 since I use VS Code on Yosemite. The App Icon for version 1.56.2 is crossed out and on startup it says: _program requires OS X 10.11 or newer_.
 

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: 10.10

Steps to Reproduce:

1. Trying to start VS Code
2. Trying on terminal with `code --disable-extensions`

Result: 
```
dyld: Symbol not found: ___NSArray0__
  Referenced from: /Users/wilfried/Downloads/Visual Studio Code 156.app/Contents/MacOS/../Frameworks/ReactiveObjC.framework/ReactiveObjC (which was built for Mac OS X 10.11)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 in /Users/wilfried/Downloads/Visual Studio Code 156.app/Contents/MacOS/../Frameworks/ReactiveObjC.framework/ReactiveObjC
./code: line 10:  1243 Trace/BPT trap: 5       ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
```

**Comment by nrayburn-tech** [comment]
10.11 is the minimum version now, https://github.com/microsoft/vscode/issues/123752.

**Comment by gjsjohnmurray** [comment]
/duplicate

Thanks @nrayburn-tech
