### ISSUE TITLE
Cannot find module '_isMockFunction'

### ISSUE THREAD

**Issue by idahogurl** [microsoft/vscode#175548]
## Description
Starting with VS Code 1.74.1, I get the following error when running tests using Jest. It works with VS Code 1.73.1
```
 Cannot find module '_isMockFunction'
    Require stack:
    - /Users/Rebecca.Vest/dev/vs-code-prettier-eslint/.vscode-test/vscode-darwin-arm64-1.74.1/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
    - /Users/Rebecca.Vest/dev/vs-code-prettier-eslint/.vscode-test/vscode-darwin-arm64-1.74.1/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
   ```

## Reproduction
1. Clone https://www.github.com/idahogurl/vs-code-prettier-eslint
2. Run `yarn` to install node modules
3. Run `yarn test`

This may be a VS Code issue.

**Comment by JustinGrote** [comment]
@idahogurl downgrading to Jest 27.5.1 fixed this for me, I don't know specifically what version this got added in but a revert does fix it.

**Comment by rbuckton** [comment]
I put together a PR to work around this for jest: https://github.com/jestjs/jest/pull/14188

I also have a workaround you can do locally. In your _start.ts_ (or whatever script you point to with `--extensionTestsPath`), add the following lines to the `run` function:

```ts
if (globalThis._VSCODE_NODE_MODULES) {
    globalThis._VSCODE_NODE_MODULES = new Proxy(saved__VSCODE_NODE_MODULES, {
        get(target, p, receiver) {
            if (p === "_isMockFunction") return undefined;
            return Reflect.get(target, p, receiver);
        }
    });
}
```

This wraps the `_VSCODE_NODE_MODULES` proxy with one that simply returns `undefined` for `_isMockFunction`.

**Comment by jrieken** [comment]
Did this get fixed in jest or is this still an issue?

**Comment by VSCodeTriageBot** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
