### ISSUE TITLE
Enter key does not jump to the definition when "Go to definition" has multiple results

### ISSUE THREAD

**Issue by AkatsukiT** [microsoft/vscode#81200]
- VSCode Version:1.38.1(user setup)
- OS Version: Windows 10 Pro 1809 x64 2019-03B
- C/C++ Extension Version: 0.25.1

When there are multiple results with "Go to definition" search, "Press Enter Key" does not jump to the definition of the selected item with "White colored font ( the default selected item)".
"Press Enter Key" will jump to the definition if the the selected item is gray colored.

The Enter key is working in the previous version 1.37.1(user setup)
related ticket(https://github.com/microsoft/vscode-cpptools/issues/4273)

Steps to Reproduce:
1.set "C_Cpp: Intelli Scese Engine" to "Tag Parser" so there will be multiple results with "Go to definition"
2.Press F12 on variables/functions which have multiple definitions
3.Press Enter
4.nothing happen

Expected behavior
Should jump to the selected result after pressing "Enter"

Does this issue occur when all extensions are disabled?: Yes (need C/C++ Extension to be enable)

The Enter key does not work in this situation.
![go_to_definition](https://user-images.githubusercontent.com/41064866/65292187-67386200-db91-11e9-81fb-e57db0af2963.jpg)
The Enter key works if I select the gray colored item.
![go_to_definition2](https://user-images.githubusercontent.com/41064866/65292191-69022580-db91-11e9-811b-150ed193337a.jpg)

**Comment by tehapo** [comment]
I'm seeing this same issue on macOS. In my case selecting the topmost result for the definition does actually respond to enter key, but the second one does not.

Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by dwelle** [comment]
For me enter doesn't work at all, regardless of number of results.

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/80362#issuecomment-533379842
