### ISSUE TITLE
vscode.dev is not working in Safari 13.1

### ISSUE THREAD

**Issue by ValeraS** [microsoft/vscode#142490]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: vscode.dev
- OS Version: MacOS Safari 13.1

Steps to Reproduce:

1. Go to vscode.dev in Safari 13.1
2. site does not loading, in dev console error "window.matchMedia(it).addEventListener is not a function. (In 'window.matchMedia(it).addEventListener(\"change\",et)'…"
https://ticino.blob.core.windows.net/sourcemaps/5554b12acf27056905806867f251c859323ff7e9/core/vs/workbench/workbench.web.api.js.map

This error was fixed, but introduced again in this commit https://github.com/microsoft/vscode/commit/4810839966fe2e9e9985d0dd9c9e099b4b63bd6f
@alexdima

**Comment by osortega** [comment]
I'm also seeing some CSP issues.
<img width="1208" alt="Screen Shot 2022-02-10 at 1 46 16 PM" src="https://user-images.githubusercontent.com/48293249/153502025-f0a9350d-8675-46ad-ac41-fcc79d08b373.png">

**Comment by alexdima** [comment]
As far as [I can tell](https://en.wikipedia.org/wiki/Safari_version_history), Safari 13 is no longer supported by Apple (i.e. does not receive security updates anymore). We only support the latest versions for each browser.

@osortega I also see a lot of CSP errors on Safari 15 when looking at release notes. I have created https://github.com/microsoft/vscode/issues/143030 to track that.
