### ISSUE TITLE
code-cli.bat broken on Windows

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#119064]
Window, VSCode repo from source

- cd to the vscode repo directory
- run `.\scripts\code.bat`: Code openes
- run `.\scipts\code-cli.bat`: Error dialog
```
[Window Title]
Error

[Main Instruction]
Error launching app

[Content]
Unable to find Electron app at C:\Users\martinae\workspaces\vscode\.build\electron

Cannot find module 'C:\Users\martinae\workspaces\vscode\.build\electron'
Require stack:
- C:\Users\martinae\workspaces\vscode\.build\electron\resources\default_app.asar\main.js
```

Seems to work on Linux

**Comment by joaomoreno** [comment]
The only change I see lately there is https://github.com/microsoft/vscode/commit/e8c71c048fab2732cbc840b1c67f5d403e975301#diff-4ee363e0cb42d025e6f8e7a711ef169ecfaaa30e36af83b657dcb208f90a0e67 @aeschli

**Comment by aeschli** [comment]
No, I already tested that. Reverting the change doesn't make a difference. 
Looks like something in Electron changed 
`".build\electron\Code - OSS.exe" .\out\cli.js .` doesn't work. 
`".build\electron\Code - OSS.exe" .\out\cli.js %CD%` works

**Comment by deepak1556** [comment]
Briefly looked at this, it works fine in `release/1.54` but not in master. There is no electron version difference between these two branches so something else broke this recently.

**Comment by joaomoreno** [comment]
@bpasero This is caused by https://github.com/microsoft/vscode/commit/1441ba91f0e3fd82ac6860aacda83befe9d176e3

**Comment by bpasero** [comment]
@joaomoreno thanks, but do you know what causes it? Is it the fact that we now `process.chdir` even for other main entry points like the cli?

Would be good for me to understand what caused the regression exactly.

**Comment by joaomoreno** [comment]
> @joaomoreno thanks, but do you know what causes it? Is it the fact that we now `process.chdir` even for other main entry points like the cli?

Yeah exactly. In `code-cli.bat` we just did `electron.exe .` which depended on staying in the original cwd (`vscode`). But with the new code, cwd always changes to where `electron.exe` is (`vscode/.build/electron`)
