### ISSUE TITLE
1.40.0 introduces uncaught exception when debugging extension

### ISSUE THREAD

**Issue by itowlson** [microsoft/vscode#84624]
Issue Type: <b>Bug</b>

I develop an extension which used to load in the Extension Development Host without errors.  Since upgrading to 1.40.0 it has started giving me the following exception.  The exception did not happen before 1.40.0.  The extension code has not changed.

```
Error: Cannot find module 'electron'
Require stack:
- d:\GitHub\vscode-kubernetes-tools\node_modules\got\index.js
- d:\GitHub\vscode-kubernetes-tools\node_modules\download\index.js
- d:\GitHub\vscode-kubernetes-tools\out\src\components\download\download.js
- d:\GitHub\vscode-kubernetes-tools\out\src\components\kubectl\autoversion.js
- d:\GitHub\vscode-kubernetes-tools\out\src\kubectl.js
- d:\GitHub\vscode-kubernetes-tools\out\src\extension.js
- c:\Users\itowlson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\itowlson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\itowlson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function._resolveFilename (internal/modules/cjs/loader.js:627:15)
	at Function.<anonymous> (internal/modules/cjs/loader.js:531:27)
	at Function.<anonymous> (c:\Users\itowlson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:796:719)
	at Function.<anonymous> (c:\Users\itowlson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:765:302)
	at Function._load (c:\Users\itowlson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:761:870)
	at Module.require (internal/modules/cjs/loader.js:685:19)
	at n (c:\Users\itowlson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at get (d:\GitHub\vscode-kubernetes-tools\node_modules\got\index.js:45:21)
	at Immediate._onImmediate (d:\GitHub\vscode-kubernetes-tools\node_modules\got\index.js:124:3)
	at processImmediate (internal/timers.js:439:21)
```

The code where is crashes is deep within VS Code, at `C:\Users\itowlson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\vs\workbench\services\extensions\node\file:\__w\1\s\src\vs\workbench\services\extensions\node\extensionHostProcessSetup.ts`.  The function is:

```
// With Electron 2.x and node.js 8.x the "natives" module
// can cause a native crash (see https://github.com/nodejs/node/issues/19891 and
// https://github.com/electron/electron/issues/10905). To prevent this from
// happening we essentially blocklist this module from getting loaded in any
// extension by patching the node require() function.
(function () {
	const Module = require.__$__nodeRequire('module') as any;
	const originalLoad = Module._load;

	Module._load = function (request: string) {
		if (request === 'natives') {
			throw new Error('Either the extension or a NPM dependency is using the "natives" node module which is unsupported as it can cause a crash of the extension host. Click [here](https://go.microsoft.com/fwlink/?linkid=871887) to find out more');
		}

		return originalLoad.apply(this, arguments);  // *** EXCEPTION HERE ***
	};
})();
```

At this point `arguments` is `["electron", (a Module object representing the 'got' NPM package), false]`.

The calling function in my user code is invoking the NPM `download` package: `await download!(sourceUrl, path.dirname(destinationFile), { filename: path.basename(destinationFile) });`

My debug settings are:

![image](https://user-images.githubusercontent.com/865538/68709711-1c6c2100-05fb-11ea-86cf-2fce00fbda72.png)

The exception _appears_ to be caught, in that I have a try-catch around that line and the `catch` is not being entered... but I have only 'uncaught exceptions' turned on.  If the exception is being caught and handled, then I guess the change in behaviour is benign, but it is very annoying as this code runs in an event handler that happens every time I start the extension!  If the exception is causing the download to fail then obviously I need to work around it for my customers.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18912

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (41.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
gitlens|eam|10.1.2
tsl-problem-matcher|eam|0.1.0
EditorConfig|Edi|0.14.2
vscode-pull-request-github|Git|0.13.0
terraform|mau|1.4.0
vscode-docker|ms-|0.8.2
duffle-vscode|ms-|0.3.0
python|ms-|2019.10.44104
remote-wsl|ms-|0.40.2
azure-account|ms-|0.8.7
csharp|ms-|1.21.7
Go|ms-|0.11.9
powershell|ms-|2019.11.0
vscode-typescript-tslint-plugin|ms-|1.2.3
quicktype|qui|12.0.46
java|red|0.52.0
vscode-yaml|red|0.6.66
rust|rus|0.7.0

</details>

**Comment by itowlson** [comment]
Looks like this is affecting customers - the exception stops the download, but does not trigger catch blocks at my top level.

I saw in the 1.40.0 release notes that you had upgraded to a new version of Electron, and given that the Electron module is mentioned in the error message, I wonder whether there is an incompatibility between Electron 6 and the `download` or `got` modules...

**Comment by itowlson** [comment]
Doing some more testing but it looks like more recent versions of `download` and `got` play nice, so if anyone else hits the same problem, that looks like the fix.

**Comment by isidorn** [comment]
Ok, so it seems like you have fixed the issue on your own by updating the modules your extension uses.
Due to that I am closing this issue. If there is still a problem with VS Code please let us know with minimal reproducable steps
