### ISSUE TITLE
Format document is not working since todays relaese

### ISSUE THREAD

**Issue by 4zriel** [Microsoft/vscode#23006]
- VSCode Version: Code - Insiders 1.11.0-insider (32942fd950cf2ffe19c44f944170014704b4fd2c, 2017-03-22T07:11:40.989Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.8.1|
|auto-close-tag|formulahendry|0.3.10|
|beautify|HookyQR|1.0.2|
|vscode-tfs|ivangabriele|0.6.0|
|PowerShell|ms-vscode|0.10.1|
|typescript-javascript-grammar|ms-vscode|0.0.18|
|debugger-for-chrome|msjsdiag|2.7.0|
|vscode-icons|robertohuertasm|7.4.0|
|autoimport|steoates|1.2.2|;

---

Steps to Reproduce:

1. From command option - Format document 
or
2. From shortcut - Ctrl Shif- F
3. Nothings happens :( 

In no insider version of vscode (below instalation details) same file (tested in typescript and html) everythings works fine.
(Version 1.10.2
Commit 8076a19fdcab7e1fc1707952d652f0bb6c6db331
Date 2017-03-08T14:02:52.799Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0)

**Comment by 4zriel** [comment]
@MaZZly As I said - for me it works on "standard" version of vscode (1.10.2) on .ts, .html and .json but no of those seems to be recognize by insiders version :/

**Comment by mjbvz** [comment]
Since this just started showing up recently in the insiders builds, I suspect this is related to #22996. Please check the developer console to confirm this

As workaround until the next insiders build is release, upgrade your workspace to TS 2.2.2 insiders or switch to using code's bundled version of TS for js and ts language features

**Comment by 4zriel** [comment]
@mjbvz  Console log:(so it looks like the same error, thx for workaround:) )
shell.ts:476Error processing request. Mismatched request id, expected undefined, actual 2
Error: Mismatched request id, expected undefined, actual 2
    at Object.resetRequest (c:\source\DEV\MAIN\Web\WUMan\node_modules\typescript\lib\cancellationToken.js:57:27)
    at IOSession.Session.resetCurrentRequest (c:\source\DEV\MAIN\Web\WUMan\node_modules\typescript\lib\tsserver.js:73291:40)
    at IOSession.Session.executeWithRequestId (c:\source\DEV\MAIN\Web\WUMan\node_modules\typescript\lib\tsserver.js:73299:26)
    at IOSession.Session.executeCommand (c:\source\DEV\MAIN\Web\WUMan\node_modules\typescript\lib\tsserver.js:73305:33)
    at IOSession.Session.onMessage (c:\source\DEV\MAIN\Web\WUMan\node_modules\typescript\lib\tsserver.js:73325:35)
    at Interface.<anonymous> (c:\source\DEV\MAIN\Web\WUMan\node_modules\typescript\lib\tsserver.js:74477:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:232:10)
    at Interface.<anonymous> (readline.js:365:12)
