### ISSUE TITLE
Debugger does not work with electron v1.6.x

### ISSUE THREAD

**Issue by ngprasad** [Microsoft/vscode#23494]
- VSCode Version: 1.10.2
- OS Version: 10.11.6

Steps to Reproduce:

1. Just update to electron v1.6.2 (latest version as of 3/28/17)
2. Place a breakpoint and it will hit the breakpoint although I don't see the stack trace or the yellow debugger line.
3. Here is the error description under the CALL STACK sub window: `No call stack available (vscode_backtrace: Internal error: TypeError: undefined is not a function)`
4. This happens with both electron 1.6.1 & 1.6.2

**Comment by weinand** [comment]
dup of #22015
Fixed in Insiders build.

**Comment by ngprasad** [comment]
Ah ok thanks @weinand. When is 1.11.0 going to be released?

**Comment by weinand** [comment]
Probably next week. But it will be almost identical to the current Insiders build.

**Comment by borgdylan** [comment]
@weinand was this affecting all debug adapters? I was seeing something similar while debugging mono apps on my machine and also Xamarin apps on my phone.

**Comment by weinand** [comment]
@borgdylan no, this is only affecting the node-debugger of VS Code.

**Comment by borgdylan** [comment]
The mono debugger was suffering the exact same thing. Pausing on a breakpoint but no yellow line and no stackframe appearing, also no immediate window responses (as no stackframe).

**Comment by weinand** [comment]
@borgdylan you are talking about this VS Code extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.mono-debug ?

**Comment by borgdylan** [comment]
@weinand Yes that one.

**Comment by weinand** [comment]
@borgdylan please create an issue [here](https://github.com/Microsoft/vscode-mono-debug/issues) and I will investigate.

**Comment by weinand** [comment]
Oh, I see you've commented already on https://github.com/Microsoft/vscode-mono-debug/issues/21
