### ISSUE TITLE
A JavaScript error occurred in the main process 

### ISSUE THREAD

**Issue by NNPhilJordan** [microsoft/vscode#172039]
Type: <b>Bug</b>

## Launch VSCode 1.74.3 after update from 1,5.x  installation, returns the following error message. 
 
Errcr 
A JavaScript error occurred in the main process 
Uncaught Exception: 
Error: Cannot find module 'C:\UsersX______\AppData\LocaI\Programs\Microsoft VS 
Code\resources\app\out\main' 
at Module. resolveFiIename 
at Function.o. resolveFiIename (node:eIectron/js2c/browser 
at (node:eIectron/js2c/browser init: 
at Object../lib/browser/init.ts (node:eIectron/js2c/browser init: 
at webpack_require_ (node: electron/js2c/browser init: I: 128) 
at node:eIectron/js2c/browser init: I: 1200 
at node:eIectron/js2c/browser init: I: 1267 
at NativeModuIe.compiIeForInternaILoader 
at NativeModuIe.compiIeForPubIicLoader (nodeinternaI/bootstrap/Ioaders:252: 10) 
at loadNativeModuIe 

## Info from VSCode
Version: 1.74.3 (system setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (1.26GB free)|
|Process Argv|--crash-reporter-id 1c832343-8e5c-4512-b4ae-98da1af45902|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (87)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
1tbs-editorconfig-generator|Alp|0.1.2
aws-toolkit-vscode|ama|1.61.0
cypress-snippets|and|1.2.0
ng-template|Ang|15.1.0
aws-amplify-vscode|aws|0.0.4
ibmi-languages|bar|0.6.8
cobol|bit|9.1.15
vscode-rpgfree|Bri|0.0.23
jsonviewer|cci|1.3.2
npm-intellisense|chr|1.4.4
vscode-eslint|dba|2.2.6
vscode-axe-linter|deq|4.5.0
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|13.2.0
EditorConfig|Edi|0.16.4
minisphere-vscode-tools|egg|0.1.0
prettier-vscode|esb|9.10.4
git-project-manager|fel|1.8.2
vscode-firefox-debug|fir|2.9.8
vscode-jest-runner|fir|0.4.60
docker-explorer|for|0.1.7
code-coverage-ibmi|hal|0.1.7
code-for-ibmi|hal|1.6.12
git-client-ibmi|hal|0.1.0
ibm-i-development-pack|hal|0.0.10
vscode-db2i|hal|0.2.9
vscode-displayfile|hal|0.0.10
vscode-ibmi-notebooks|hal|0.0.5
vscode-ibmi-walkthroughs|hal|0.2.4
vscode-rpgle|hal|0.17.2
vscode-dynamodb|har|0.0.1
vscode-clle|IBM|1.1.0
terraform-ssm|ita|0.3.6
create-migration|Iva|0.0.1
netdata|jar|1.0.6
angular-essentials|joh|13.0.0
Angular2|joh|13.0.0
vscode-peacock|joh|4.2.2
cypress-fixture-intellisense|Jos|1.2.0
dotnet-core-essentials|Kis|0.0.8
vscode-gutter-preview|kis|0.30.0
ef-core-snippets|Lew|1.0.0
lambda-snippets|log|1.0.0
aws-cli-configure|mar|0.3.0
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.23.3
csharp|ms-|1.25.2
remote-containers|ms-|0.266.1
remote-wsl|ms-|0.72.0
notepadplusplus-keybindings|ms-|1.0.7
powershell|ms-|2023.1.0
vsliveshare|ms-|1.0.5808
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-edge|msj|1.0.15
ibm-i-run-sql-from-acs|Nie|0.0.4
angular-console|nrw|17.28.2
vscode-boot-dev-pack|Piv|0.2.0
vscode-concourse|Piv|1.43.0
vscode-manifest-yaml|Piv|1.43.0
vscode-spring-boot|Piv|1.43.0
material-icon-theme|PKi|4.23.1
dynamodb-vscode-snippets|raf|0.0.6
vscode-thunder-client|ran|2.3.4
java|red|1.14.0
vscode-xml|red|0.23.0
vscode-scss-formatter|sib|2.4.4
sonarlint-vscode|Son|3.13.0
rewrap|stk|1.16.3
pdf|tom|1.2.2
errorlens|use|3.6.0
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.4
vscode-spring-boot-dashboard|vsc|0.9.0
vscode-spring-initializr|vsc|0.11.2
vscode-aws-console|vsc|0.0.5
vscode-todo-highlight|way|1.0.5
targetframeworksswitcher|yam|1.0.3
vscode-games|yiw|0.0.4
project-tree|zhu|0.3.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
vscsbc:30628655

```

</details>

**Comment by bpasero** [comment]
Can you uninstall and reinstall VS Code fully?

**Comment by NNPhilJordan** [comment]
Hi! Would you have any tools to save config information. My setup has a number of extensions as well as NPM, Git, etc. Uninstall will be a multi-hour effort.

**Comment by NNPhilJordan** [comment]
Thanks! I do not use the portable option.

**Comment by NNPhilJordan** [comment]
No success -  uninstalled via system apps removal, restarted, and re-installed. Other options/ideas?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by deepak1556** [comment]
@NNPhilJordan can you also provide the full error output from `code --verbose`, thanks!

**Comment by bpasero** [comment]
This sounds in the end like a setup problem on your machine and not something we can fix on our side. I suggest to consult IT support.

**Comment by NNPhilJordan** [comment]
Disappointed in this resolution. May want to ensure your product is more solid at release. 3rd time I am experiencing work-stopping install issues in last 9 months.

**Comment by deepak1556** [comment]
@NNPhilJordan can you list the contents of the directory `C:\Users\pjordan\AppData\LocaI\Programs\Microsoft VS
Code\resources\app\out\`

**Comment by NNPhilJordan** [comment]
Hi! The out directory does not exist in ...\app. This has been the recurring problem - the resources are not there.

**Comment by NNPhilJordan** [comment]
A colleague and I reviewed the setup. Since there were prior versions of VSCode still installed, I removed those versions from apps, corrected the link to point to this 'system' version of the code, and I am no longer getting this error. Hope this helps in the future: Add  a reminder to install instructions to remove prior versions after new install and before using newly code. Also verify Startup or shortcuts used point to new code.

**Comment by deepak1556** [comment]
> Since there were prior versions of VSCode still installed, I removed those versions from apps, corrected the link to point to this 'system' version of the code

Can you expand a bit more on this setup flow, what links did you correct ? Also, are you manually updating VSCode given this description.

**Comment by NNPhilJordan** [comment]
From the short cut created...
Target was: C:\users\pjordan\AppData\local\Programs\Microsoft VS Code\Code.exe
Target is: "C:\Program Files\Microsoft VS Code\Code.exe"

**Comment by deepak1556** [comment]
IIUC, your setup is that you have user installation of VSCode but have created symlinks at the `Program Files` location so that it could shared with other users on the system ? This is not a setup our updater can support, you should use system installation for these scenarios https://code.visualstudio.com/#alt-downloads

<img width="291" alt="Screenshot 2023-01-27 at 11 30 32" src="https://user-images.githubusercontent.com/964386/214997994-179312e5-dbeb-40b1-a5bf-9064738e39d3.png">

**Comment by NNPhilJordan** [comment]
Understood - original install was 'single user'. When I found that 1.70.x would not remind me of Updates found a reminder in Stack Overflow that suggested the 'system install'. Did not realize only one instance of VSCode could be on system at a time.  That is the solution to this issue - one instance of VSCode at a time. Lesson Learned back up all the settings before doing these installs.
