### ISSUE TITLE
PNPM | Typescript use workspace version: error reading source file in tsserver

### ISSUE THREAD

**Issue by frederikdekegel** [microsoft/vscode#92864]
- VSCode Version: 1.43.0
- OS Version: Windows 10 build 17763
- Typescript version: 3.5.3

### Steps to Reproduce:

1. Have a project that uses typescript and pnpm as a package manager (in my case Angular project).  
2. Set Visual Studio Code to use the Workspace version of typescript (installed with pnpm).
3. Open a typescript file

### Error
After opening the file c:/VSP/Web/eServices/pnpm/Apps/acv-csc/apps/contact/src/app/_components/physical-direct-contact-detail/physical-direct-contact-detail.component.ts, the tsserver reports that it cannot find the typescript file that was just opened.

<pre><code>
ERR <semantic> TypeScript Server Error (3.5.3)
Could not find sourceFile: 'c:/VSP/Web/eServices/pnpm/Apps/acv-csc/apps/contact/src/app/_components/physical-direct-contact-detail/physical-direct-contact-detail.component.ts'.
Error: Could not find sourceFile: 'c:/VSP/Web/eServices/pnpm/Apps/acv-csc/apps/contact/src/app/_components/physical-direct-contact-detail/physical-direct-contact-detail.component.ts'.
    at getValidSourceFile (C:\VSP\Web\eServices\pnpm\Apps\acv-csc\node_modules\.pnpm\registry.npmjs.org\typescript\3.5.3\node_modules\typescript\lib\tsserver.js:121885:23)
    at Proxy.getEncodedSemanticClassifications (C:\VSP\Web\eServices\pnpm\Apps\acv-csc\node_modules\.pnpm\registry.npmjs.org\typescript\3.5.3\node_modules\typescript\lib\tsserver.js:122351:102)
    at IOSession.Session.getEncodedSemanticClassifications (C:\VSP\Web\eServices\pnpm\Apps\acv-csc\node_modules\.pnpm\registry.npmjs.org\typescript\3.5.3\node_modules\typescript\lib\tsserver.js:130565:53)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (C:\VSP\Web\eServices\pnpm\Apps\acv-csc\node_modules\.pnpm\registry.npmjs.org\typescript\3.5.3\node_modules\typescript\lib\tsserver.js:130133:61)
    at C:\VSP\Web\eServices\pnpm\Apps\acv-csc\node_modules\.pnpm\registry.npmjs.org\typescript\3.5.3\node_modules\typescript\lib\tsserver.js:131671:88
    at IOSession.Session.executeWithRequestId (C:\VSP\Web\eServices\pnpm\Apps\acv-csc\node_modules\.pnpm\registry.npmjs.org\typescript\3.5.3\node_modules\typescript\lib\tsserver.js:131662:28)
    at IOSession.Session.executeCommand (C:\VSP\Web\eServices\pnpm\Apps\acv-csc\node_modules\.pnpm\registry.npmjs.org\typescript\3.5.3\node_modules\typescript\lib\tsserver.js:131671:33)
    at IOSession.Session.onMessage (C:\VSP\Web\eServices\pnpm\Apps\acv-csc\node_modules\.pnpm\registry.npmjs.org\typescript\3.5.3\node_modules\typescript\lib\tsserver.js:131693:35)
    at Interface.<anonymous> (C:\VSP\Web\eServices\pnpm\Apps\acv-csc\node_modules\.pnpm\registry.npmjs.org\typescript\3.5.3\node_modules\typescript\lib\tsserver.js:132984:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17): Error: <semantic> TypeScript Server Error (3.5.3)
</code></pre>

### Consequence
- No syntax error reporting.

### Additional info
Other references from Visual Studio Code to node_modules also fail. Like lightbulb to import packages.

### Extra
Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
You are using an old TS version (3.5). Does this work with TypeScript 3.8+?

**Comment by mjbvz** [comment]
Closing as using an old TS version

**Comment by frederikdekegel** [comment]
After upgrading to Angular 9.1.0 and thus Typescript 3.8.3, the error has disappeared. Error checking within a typescript script file is again functional. However, the lightbulb import package functionality does not work. There is no error unfortunately.

I will create a new issue to report this.
