### ISSUE TITLE
Typescript issue with diagnostics and syntax highlighting

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#70971]
Issue Type: <b>Bug</b>

Seeing some strange highlighting and incorrect problems:
![Screen Shot 2019-03-22 at 10 15 57 AM](https://user-images.githubusercontent.com/3672607/54841200-01bff300-4c8c-11e9-99f8-8e618998bf5e.png)

I was rebasing something and had conflicts in that file with the import statements. I chose one of the options, I think keeping the incoming code, so I was expecting the diagnostics to change to issues about missing or unused imports. Instead there are now bizarro things like "Cannot find name 'constructor'" on an empty line.

Here's the output from the ts channel, I couldn't easily find where things went sideways so I just included everything:

[trace.txt](https://github.com/Microsoft/vscode/files/2997639/trace.txt)

After restarting the TS server everything is back to normal and the only problems are on unused import statements.

VS Code version: Code - Insiders 1.33.0-insider (9474154f133dbbb793ca3c128c9fcfdca39f5b26, 2019-03-22T06:15:30.293Z)
OS version: Darwin x64 18.2.0

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.20
gitlens|eam|9.5.1
vscode-pull-request-github-insiders|Git|1.79.0
graphql-for-vscode|kum|1.13.0
vscode-language-pack-de|MS-|1.33.0
vscode-language-pack-es|MS-|1.33.0
vscode-language-pack-fr|MS-|1.33.0
vscode-language-pack-zh-hans|MS-|1.33.0
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.1
polacode|pnp|0.2.2

</details>

**Comment by RMacfarlane** [comment]
Ah, I also had to restart my build watch task after rebasing, it started showing a bunch of erroneous errors, too. What I pulled in added no implicit any checking and possibly other configuration or package changes.

**Comment by Nsbx** [comment]
Same problem here, this error appear often when i made copy and paste.
And same way to solve, restart the ts server (or restart vscode but is more long)

**Comment by FishOrBear** [comment]
I also encountered such a problem, this error often occurs.

**Comment by mjbvz** [comment]
Closing this as I have not seen recent reports of this. If you see this again, please let me know
