### ISSUE TITLE
--install-extension UnhandledPromiseRejectionWarning: Unhandled promise rejection

### ISSUE THREAD

**Issue by jimsloan** [Microsoft/vscode#32464]
- VSCode Version: 1.15
- OS Version: Ubuntu 17.04, Windows 10

Steps to Reproduce:

1. Install/Upgrade VSCode 
2. Use command line to install extension
Reproduces without extensions: Yes

```
$ code --install-extension ms-vscode.cpptools
Found 'ms-vscode.cpptools' in the marketplace.
Installing...
(node:27414) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this._state.then is not a function
(node:27414) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Works on VSCode Version 1.14.2
Install from .vsix works fine

**Comment by joaomoreno** [comment]
#32381

**Comment by gpuido** [comment]
As an alternative for now is there a way to use this URL to get the last version without knowing the ${version} number ?

http://${publisher}.gallery.vsassets.io/_apis/public/gallery/publisher/${publisher}/extension/${extension name}/${version}/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

I'm looking for something like ${version} = x.x.x or something that the server handle to give the last vsix.




referenced here
https://code.visualstudio.com/docs/editor/extension-gallery#_common-questions
