### ISSUE TITLE
files not opening after update to 1.36

### ISSUE THREAD

**Issue by AmitRavi** [microsoft/vscode#75815]
Issue Type: <b>Bug</b>

Use in the in app update feature to update vs code insiders to 1.36. 
None of the files open and an error is popped on at the right bottom corner - Unable to open '<filename>': r.onMouseLeave is not a function.

VS Code version: Code - Insiders 1.36.0-insider (6520c22b83c0b6f168ba7de3309ffab42281e905, 2019-06-19T05:19:10.147Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.58GB (6.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.2
auto-close-tag|for|0.5.6
Angular2|joh|8.1.1
Angular-BeastCode|Mik|8.0.7
vscode-typescript-tslint-plugin|ms-|1.2.0
debugger-for-chrome|msj|4.11.4
vscode-scss-formatter|sib|1.4.1
autoimport|ste|1.5.3
vscode-icons|vsc|8.7.0

</details>

**Comment by isidorn** [comment]
I can not reproduce this. Can you repro if you use latest vscode insiders with no extensions https://code.visualstudio.com/insiders/
If you F1 > developer tools > break on error can you get a more meaningful stack trace please?
