### PR TITLE
chore: revert to electron@13

### PR DESCRIPTION
**Pull request by deepak1556**
Electron 16 update will be adopted in March 2022 milestone due to release [blockers](https://github.com/microsoft/vscode/labels/electron-blocker)

PR contains following changes:

- Reverts https://github.com/microsoft/vscode/commit/01df559c184549248fcfbcecc5a616462e00c252 , with following exceptions
   - Does not enable back breakpad support for extension host
   - Does not revert layer checker changes
   - Only made api changes were needed due to compilation errors
- Reverts https://github.com/microsoft/vscode/commit/46301339b71e7f99187edd262b809e8788bcb358 because the napi headers shipped with Electron 13 does not work with Keytar > 7.6.0 /cc @TylerLeonhardt 

Will reopen the following issues once this PR gets merged,

https://github.com/microsoft/vscode/issues/120431
https://github.com/microsoft/vscode/issues/133820
https://github.com/microsoft/vscode/issues/131714
https://github.com/microsoft/vscode/issues/93615
https://github.com/microsoft/vscode/issues/136787
https://github.com/microsoft/vscode/issues/50386
https://github.com/microsoft/vscode/issues/138721
https://github.com/microsoft/vscode/issues/84453
[fixed-in-electron-16 query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Afixed-in-electron-16+is%3Aclosed)

### CODE REVIEW

**Review by bpasero — CHANGES_REQUESTED** [review]
As discussed I would suggest to do a full revert of the commits that went in first and then do selected changes on top that we want to keep. That would ensure we are not shipping a partial untested change.

I would suggest a PR composed of these commits:
* revert of the big E16 change
* revert of E16 associated changes (such as keytar update)
* 1 commit that selectively restores changes as needed

That would also make it much easier to review.

**Review by bpasero — APPROVED** [review]
