### ISSUE TITLE
[Bug] TypeError: h is not a function opening remote files after upgrading VS Code to 1.123, works fine on 1.122 with same SSH FS v1.26.1

### ISSUE THREAD

**Issue by wjjook** [microsoft/vscode#320218]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.123
- OS Version:  windows11

Steps to Reproduce:

1. SSH FS v1.26.1 works perfectly on VS Code 1.122, no errors when browsing or opening remote SFTP files.
After upgrading VS Code to 1.123, I can browse remote directory list normally, but opening any remote file throws runtime error TypeError: h is not a function.
Full error stack:
TypeError: h is not a function
	at D (c:\Users\wjjoo\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\14f8.extension.js:1:145959)
	at SFTP.open (c:\Users\wjjoo\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\14f8.extension.js:1:167395)
	at se.open (c:\Users\wjjoo\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\14f8.extension.js:1:161216)
	at new se (c:\Users\wjjoo\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\14f8.extension.js:1:160219)
	at SFTP.createReadStream (c:\Users\wjjoo\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\14f8.extension.js:1:166937)
	at c:\Users\wjjoo\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\f1d0.extension.js:1:2898
	at new Promise (<anonymous>)
	at g.readFile (c:\Users\wjjoo\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\f1d0.extension.js:1:2859)
	at c.readFile (c:\Users\wjjoo\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\extension.js:1:53039)
No changes to SSH FS version (still fixed v1.26.1), no changes to remote Ubuntu(Raspberry Pi CM5) server or SFTP connection config.
Steps to reproduce
Keep SSH FS fixed at v1.26.1
VS Code 1.122: connect SFTP to remote Ubuntu, open any remote file → success
Upgrade VS Code to 1.123, keep extension unchanged
Reuse identical existing SFTP connection: view folder tree OK, double-click any file → crash with above TypeError
Expected behavior
Remote file opens normally on VS Code 1.123 just like on 1.122.
Environment
OS: Windows
VS Code: 1.123 (broken) / 1.122 (working)
Extension: SSH FS v1.26.1
Remote OS: Ubuntu 24.04 (Raspberry Pi CM5)
Additional info
Downgrade VS Code back to 1.122 resolves the issue instantly; problem is purely compatibility break between this extension and VS Code 1.123 new Electron/Node runtime.

**Comment by gjsjohnmurray** [comment]
/causedByExtension which uses a long-deprecated function that finally got removed in Node 24

**Comment by gjsjohnmurray** [comment]
#319963
