### ISSUE TITLE
Debug starts and stops a few seconds later with no log

### ISSUE THREAD

**Issue by scottpageindysoft** [microsoft/vscode#120762]
Issue Type: <b>Bug</b>

I was able to debug as I have been for well over a year with this project, until I updated to Insiders 1.56 this afternoon.  Upon VSCode restarting, I started a debug session, the debugger stopped after a few seconds, and left no errors or logs.

I completely wiped vscode-insiders from my system, deleted all extension and trace of it existing, then installed again.  Same issue.

I noticed that the node-debug (ms-vscode.node-debug2) dependancy was updated, twice, yesterday.  I'm suspecting something isn't right with that extension, but it's built-in, so no rolling back without downgrading VSCode.

node-debug changes, yesterday:
https://github.com/microsoft/vscode/commit/4202acc9f765154b404d8287c0243a03b57a9e0b
https://github.com/microsoft/vscode/commit/accd84def608169a720b4e58ef30debf9490e653

VS Code version: Code - Insiders 1.56.0-insider (Universal) (bb90ba3d5a5f8d114045b045f3bbe1ebc404f54a, 2021-04-07T13:06:58.816Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.77GB free)|
|Process Argv|--crash-reporter-id 486ee961-8c9a-4d09-b0f1-e085c767cff1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.4
vscode-eslint|dba|2.1.19
gitlens|eam|11.3.0
todo-tree|Gru|0.0.209
vue-snippets|hol|1.0.4
node-module-intellisense|lei|1.5.0
vscode-antlr4|mik|2.2.4
vscode-docker|ms-|1.11.0
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.8
vscode-typescript-next|ms-|4.3.20210406
vetur|oct|0.33.1
vscodeintellicode|Vis|1.2.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
vstes627:30244334
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
wslfolderdoc:30278405
vscoresta800:30283263
vspre833:30267464
pythonptprofiler:30281269
vscnewfiletext:30280636
vshan820:30276952
pythondataviewer:30285072

```

</details>

**Comment by scottpageindysoft** [comment]
I checked the extension host log and found this:
[Log (Extension Host)](https://gist.github.com/scottpageindysoft/557dc59d94999d856cff6471af0758f5)

Notice the error "Cannot find module '/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.node-debug/dist/extension.js'"

**Comment by weinand** [comment]
This issue only affects node-debug (legacy) for node.js legacy versions < 8.0.
For all other version of node.js the new js-debug is used, which works fine in Insiders 1.56.

node-debug (legacy) should be fixed in tomorrow's insiders.

**Comment by scottpageindysoft** [comment]
Sounds good.  I am using legacy, so good catch.

Appreciate the quick mitigation.

**Comment by thaoula** [comment]
Hi @weinand,

Excuse the possibly stupid question but how do you switch from node-debug -> js-debug?

I cannot find any reference to this.

Regards,
Tarek

**Comment by weinand** [comment]
Normally, the switching between node-debug and js-debug happens automatically behind the scenes.
But since "node-debug" was broken in Insiders, your approach of configuring "pwa-node" explicitly is the correct workaround.
