### ISSUE TITLE
After upgrading to 1.49, code intellisense is not working for node js (common js)

### ISSUE THREAD

**Issue by amitguptagwl** [microsoft/vscode#106609]
- VSCode Version: 1.49.0
- Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
- Date: 2020-09-10T13:20:50.359Z
- Electron: 9.2.1
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Linux x64 5.4.0-47-generic snap
- OS Version: Ubuntu 18.04 x64

Steps to Reproduce:

1. Create a node js project.
2. Create a js file.
3. import fs or path modules

![Screenshot from 2020-09-14 05-59-10](https://user-images.githubusercontent.com/7692328/93032530-b5baf800-f64f-11ea-8e7d-7b7cca3335a5.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does any IntelliSense work, such as for standard library functions? What shows if you hover over `fs`?

**Comment by amitguptagwl** [comment]
@mjbvz It says "Cannot find module 'fs' or its corresponding type declarations.ts(2307)". However, when I run the code, there is no issue.

**Comment by mjbvz** [comment]
Can you share more info about your project. Do you have a `package.json` file for example?

**Comment by amitguptagwl** [comment]
Yes, it has package.json file, node_modules folder

**Comment by mjbvz** [comment]
Please share an example project

**Comment by amitguptagwl** [comment]
I had to format system and reinstall vscode. Currently I'm checking with v1.50.1. And it is working fine. So closing the issue. I'm wondering if it is a clash with some plugin. Because on new installation I have not installed any plugin yet. However, I'll check this again with plugins and report if I face the issue again.
