### PR TITLE
fix: use addListener instead of addEventListener to to observe media query lists

### LINKED ISSUE #2432: Monaco editor is not working in Safari 13.1
**monaco-editor version:** 0.23.0
**Browser:** Safari 13.1
**OS:** Mac

Upgrading the Monaco editor in our web application from version 0.21.2 to 0.23.0 has stopped our application loading in Safari 13.1. Updating to the latest version of Safari 14.0.3 does fix the issue. However we need to continue to support Safari 13 in the short-term.

We see the following error:

window.matchMedia("(forced-colors: active)").addEventListener is not a function. (In 'window.matchMedia("(forced-colors: active)").addEventListener("change",(function(){e._updateActualTheme()}))', 'window.matchMedia("(forced-colors: active)").addEventListener' is undefined)

This is reproducible on https://microsoft.github.io/monaco-editor/:

Screenshot 2021-04-09 at 17 02 02

It appears that this is the recent code change that has caused the issue: https://github.com/microsoft/vscode/blob/58faca759ab38b44837c512074fa942f4716a9fa/src/vs/editor/standalone/browser/standaloneThemeServiceImpl.ts#L236

I assume that Safari 13.1 does not implement addEventListener on MediaQueryList, so addListener needs to be used instead.

### PR DESCRIPTION
**Pull request by ValeraS**
Prior Safari 14, MediaQueryList does not have method addEventListener,
use addListener for backward compatibility, which is supported by all browsers.

This PR fixes https://github.com/microsoft/monaco-editor/issues/2432

### CODE REVIEW

**Review by glaukiol1 — APPROVED** [review]
Simple fix, thanks for contributing! Approved by me

**Review by alexdima — CHANGES_REQUESTED** [review]
I cannot accept the PR as is. MDN strongly discourages using `addListener`. At least this should be done that it first checks if `addEventListener` exists and if not, then fall back to `addListener`.

https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener

image

**Review by alexdima — APPROVED** [review]
LGTM. We are currently locking down our `main` for the upcoming vscode release, I will merge this early next week.

**Comment by tenphi** [comment]
Thanks for the contribution. @ValeraS 
A gentle reminder for @alexdima about merging this PR. It's hard to monkey-patch or polyfill this. We have a few complaining users.
