### ISSUE TITLE
foreignModule.create is not a function

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#49692]
I got this exception whenever I open the output. Both in insiders and out of source

loader.js:257 TypeError: foreignModule.create is not a function
    at editorSimpleWorker.ts:532
    at Function.Module._safeInvokeFunction (loader.js:927)
    at Function.Module._invokeFactory (loader.js:946)
    at Module.complete (loader.js:959)
    at ModuleManager._onModuleComplete (loader.js:1558)
    at ModuleManager._onModuleComplete (loader.js:1570)
    at ModuleManager._resolve (loader.js:1520)
    at ModuleManager.defineModule (loader.js:1185)
    at ModuleManager._onLoad (loader.js:1262)
    at Object.callback (loader.js:1431)

**Comment by alexandrudima** [comment]
@isidorn This is caused by https://github.com/Microsoft/vscode/commit/fa8ce667fffff182667eab7c147717293919ec9a#diff-7f36b7cf562040f8117733a7acabe7ae

Specifically the deletion of this method:
![image](https://user-images.githubusercontent.com/5047891/40043005-78b8b3f6-5823-11e8-9784-d0ba8c225ace.png)

**Comment by isidorn** [comment]
@alexandrudima thanks for finding that - I could not find any references to this method thus I deleted it, was not aware it was being used in a different way
