### PR TITLE
Add support for extracting environment from xonsh.

### LINKED ISSUE #200374: With xonsh shell, unable to resolve shell environment
Type: <b>Bug</b>

I use the [xonsh](http://xon.sh/) shell:

```
 ~ @ finger $USER | grep 'Shell:*' | cut -f3 -d ":"
 /Users/jaraco/.local/bin/xonsh
```

When I start VS Code not from the terminal, I see a popup with the error:

```
Unable to resolve your shell environment: Unexpected exit code from spawned shell (code 1, signal null)
```

I know why this issue occurs - it's because VS Code is assuming bash semantics for launching the user's shell in order to solicit environment variables. I encountered the [same issue with PyCharm/Jetbrains](https://youtrack.jetbrains.com/issue/IDEA-278044/Failed-to-load-environment-xonsh).

In that report, I reached out to the xonsh project (xonsh/xonsh#4469) to see if the shell might be able to support bash syntax for this purpose, but after some consideration, they rejected the idea, instead asking editors to honor the shell.

Here I'm making the same request to VS Code, namely that if the shell is xonsh ("xonsh" appears in the user's shell path), to use a syntax specialized for xonsh to extract the user's environment, namely:

```
xonsh -c "$['/tmp/printenv' > 'outfile']"
```

If direct support for xonsh can't be added, would you consider adding a configuration variable such that a user of xonsh could customize VS Code to honor xonsh as the default shell?

VS Code version: Code 1.85.0 (Universal) (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T18:18:04.614Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 5, 6|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id b169758f-2f18-42cf-8f71-cd2543a7a74c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.141.0
copilot-chat|Git|0.11.0
black-formatter|ms-|2023.6.0
isort|ms-|2023.10.1
python|ms-|2023.22.0
vscode-pylance|ms-|2023.11.10
sublime-keybindings|ms-|4.0.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260

```

</details>

### PR DESCRIPTION
**Pull request by jaraco**
Closes #200374.

### CODE REVIEW

**Comment by jaraco** [comment]
I haven't tested this change beyond confirming that `xonsh -i -l -c '$[<command>]'` works syntactically:

```
 @ xonsh -i -l -c '$[echo foo]'
foo
```

Is there a way I can get a build with the change to confirm it fixes the reported issue?

File: src/vs/platform/shell/node/shellEnv.ts [hunk 1]
```diff
@@ -137,6 +137,9 @@ async function doResolveUnixShellEnv(logService: ILogService, token: Cancellatio
 		} else if (name === 'nu') { // nushell requires ^ before quoted path to treat it as a command
 			command = `^'${process.execPath}' ${extraArgs} -p '"${mark}" + JSON.stringify(process.env) + "${mark}"'`;
 			shellArgs = ['-i', '-l', '-c'];
+		} else if (name === 'xonsh') { // #200374: xonsh expects escaping to avoid Python syntax
+			command = `$['${process.execPath}' ${extraArgs} -p '"${mark}" + JSON.stringify(process.env) + "${mark}"']`;
```
Comment (jaraco) [inline src/vs/platform/shell/node/shellEnv.ts:141]: My preference would be not to repeat the whole command, but since that's the pattern that was established by `nu`, I wanted to be minimally invasive and follow the patterns already in use.

**Comment by jaraco** [comment]
I read the instructions and figured out how to make a local build of VSCode and ran `./scripts/code.sh`, but I couldn't replicate the failure on `main`. I presume the issue is that the code path isn't triggered when launched from the CLI. I thought I might be able to simulate the non-shell environment by launching with `env -i PATH=$PATH ./scripts/code.sh`, but even then, the issue doesn't replicate.

Next, I read the code and learned about `--force-user-env` and using that I was able to replicate the failure. With the patch, the failure still occurs, so I'll need to investigate further.

**Comment by jaraco** [comment]
By running with `--log trace`, I can see the command that's being run:

```
[main 2023-12-17T16:38:29.119Z] getUnixShellEnvironment#shell /Users/jaraco/.local/bin/xonsh
[main 2023-12-17T16:38:29.119Z] getUnixShellEnvironment#spawn ["-i","-l","-c"] $['/Users/jaraco/code/microsoft/vscode/.build/electron/Code - OSS.app/Contents/MacOS/Electron'  -p '"280993a1c165" + JSON.stringify(process.env) + "280993a1c165"']
```

**Comment by jaraco** [comment]
When I run that command manually

```
 @ xonsh -c '$[\'/Users/jaraco/code/microsoft/vscode/.build/electron/Code - OSS.app/Contents/MacOS/Electron\'  -p \'"280993a1c165" + JSON.stringify(process.env) + "280993a1c165"\']'
```

(I had to escape the inner `'` characters.

it fails thus:

image


Text in that image:

```
Unable to find Electron app at /Users/jaraco/code/microsoft/vscode/"280993a1c165" + JSON.stringify(process.env) + "280993a1c165"

Cannot find module '/Users/jaraco/code/microsoft/vscode/"280993a1c165" + JSON.stringify(process.env) + "280993a1c165"'
Require stack:
- /Users/jaraco/code/microsoft/vscode/.build/electron/Code - OSS.app/Contents/Resources/default_app.asar/main.js
-
```

**Comment by jaraco** [comment]
I haven't yet figured out why the invocation of Electron is failing but in c62c575, I replaced the electron invocation with a native JSON rendering of the environment in xonsh, and I've confirmed this approach fixes the issue.

Is this approach acceptable?

Is there any idea why Electron is failing the way it is?

**Review by Tyriar — APPROVED** [review]
As long as the output is identical to the JSON output (or at least parsed in the same way in node), the current approach is fine. It's probably better actually as that way we don't need to launch node.

Let's merge this, please let me know if there are problems with it when it ships as the only way to test this properly is to get a real build post-merge and try launching from the dock.

**Review by lramos15 — APPROVED** [review]
