### ISSUE TITLE
After upgrade to 1.55, secrets previously stored with `context.secrets` are no longer accessible

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#120558]
- VS Code Version: 1.55.0
- OS Version: Win10 20H2

Steps to Reproduce:

1. Install VSCode 1.54.3
1. Install the Docker extension
1. Connect to Docker Hub, using "Docker Registries: Connect Registry..."
1. This will ask for a Docker Hub username and password. The username is stored in a memento and the password using the `SecretStorage` API.
1. Upgrade to VSCode 1.55.0
1. Try to access the Docker Hub registry, or do "Docker: Log In to Docker CLI"

Result: An error is shown. `(n.stack || "").split is not a function`. This is a red herring due to some bugged error parsing we're doing (microsoft/vscode-azuretools#860), but the _real_ error is: "Error: Decryption failed"

I haven't tried this with a dummy extension but presumably the same would occur.

Does this issue occur when all extensions are disabled?: N/A

**Comment by bwateratmsft** [comment]
@RMacfarlane FYI

**Comment by bwateratmsft** [comment]
I spoke to @RMacfarlane and I guess this is expected; there was a change in the encryption on Windows that requires reentering the secrets.

**Comment by mattmilten** [comment]
Is there some workaround or how can you recreate the secrets to get around the failed decryption?

**Comment by bwateratmsft** [comment]
@mattmilten That will depend on the extension. For example, with the Docker extension, the simplest way is to disconnect from the container registry, and then reconnect (which will prompt again for username and password).

**Comment by mattmilten** [comment]
Thanks! For me it's the Jupyter extension - I cannot start an interactive window or even select the Jupyter server when in a remote-ssh session. I already tried removing all related settings and restarted as suggested in #5419.

**Comment by RMacfarlane** [comment]
Closing this as this is expected for this release.
