### ISSUE TITLE
vscode (>= 1.59) extension development cannot find module

### ISSUE THREAD

**Issue by linancn** [microsoft/vscode#133053]
Issue Type: <b>Bug</b>

1. In any vscode extension development, vscode version >= 1.59 (no bug when vscode version <= 1.58, the very same code works fine in <= 1.58 )

2. "dependencies": "mysql": "~2.15.0"
"devDependencies": "@types/mysql": "~2.15.19"

3. import 'mysql' in any ts file other than extension.ts (no bug in extension.ts)
ex.: import { createConnection, Connection, ConnectionConfig } from 'mysql';

4. debug, then error shows up：
Activating extension 'XXX' failed: Cannot find module '/XXX/node_modules/mysql/lib/Connection'.

Is it missing the file extension name '.js'???

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|64.00GB (50.13GB free)|
|Process Argv|--crash-reporter-id b035a12e-eedf-44e1-8faf-fc6ff3f5c36e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.0
vscode-eslint|dba|2.1.25
vscode-npm-script|eg2|0.3.22
rainbow-csv|mec|1.9.1
vscode-docker|ms-|1.16.1
python|ms-|2021.9.1230869389
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.194.0
vscode-typescript-tslint-plugin|ms-|1.3.3
vscode-boot-dev-pack|Piv|0.1.0
vscode-spring-boot|Piv|1.28.0
material-icon-theme|PKi|4.10.0
java|red|0.81.0
java-generate-setters-getters|soh|7.3.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.7.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187cf:30365362
pydsgst2:30361792
vscus224:30358039
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by roblourens** [comment]
It sounds like this is an issue with your install or usage of the mysql npm module. I don't know what the problem is and can't help troubleshoot it, sorry
