### ISSUE TITLE
Cannot debug electron on windows

### ISSUE THREAD

**Issue by andyboyne** [microsoft/vscode#102099]
VSCode Version: 1.47.0
OS Version: Windows 10 1809
Node version: 14.2.0

**Steps to reproduce:**
Try running an electron app that previously worked in 1.46.1, with or without the debugger attached.

**More info:**
After installing 1.47 I get the follow error upon running with or without debugging enabled:

```
internal/modules/cjs/loader.js:662
    throw err;
    ^
Error: Cannot find module '"c:/Users/{redacted username}/AppData/Local/Programs/Microsoft'
Require stack:
- internal/preload
```

- The path looks incorrect as the full path should end in "Microsoft VS Code", but is truncated to simply "Microsoft".

- If I manually rename the folder to remove the spaces, it gets further but blows up with another error:

```
internal/modules/cjs/loader.js:662
    throw err;
    ^

Error: Cannot find module '"c:/Users/{redacted username}/AppData/Local/Programs/MicrosoftVSCode/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js"'
Require stack:
- internal/preload

```

similar but not identical to: #102069

**Comment by gjsjohnmurray** [comment]
@andyboyne does [this workaround](https://github.com/microsoft/vscode/issues/102069#issuecomment-656610397) help you?

**Comment by andyboyne** [comment]
> @andyboyne does [this workaround](https://github.com/microsoft/vscode/issues/102069#issuecomment-656610397) help you?

That workaround does appear to help, thanks. However, looking at some of the other issues being raised I'm going to stick with 1.46.1 for now and disable automatic updates from now on.

**Comment by connor4312** [comment]
@andyboyne Electron can run with a Node version different than the one on your PATH, which I suspect is causing an issue for you. There are a couple good options, aside from disabling updates:

1. [Use the latest nightly version](https://github.com/microsoft/vscode-js-debug/#nightly-extension) of the debugger and add `nodeVersionHint: 10` to signal that we'll run with an older Node version.
2. Add `debug.javascript.usePreview: false` to use the old debugger until a fix for this is release
3. Update to the latest Electron version

Duplicates https://github.com/microsoft/vscode/issues/102035#issuecomment-656750889

**Comment by connor4312** [comment]
@andyboyne can you please also confirm which version of electron you were using?

**Comment by andyboyne** [comment]
This is nothing to do with node. I use explicit paths, and do not have node installed globally. I am using node 14. There is no other node on the path.

Stop closing issues on an assumption, clearly there are issues otherwise we wouldn’t raise them.

It’s electron 5 but it blows up way before that’s as clearly demonstrated by the provided stack traces.

**Comment by connor4312** [comment]
Okay, thanks for confirming. The issue is indeed the Node version bundled in Electron 5 -- the fact that you have Node 14 globally is actually part of the problem here, since we assume that's what the executable you're running is using!

Electron 6 and higher bundles a more recent version of Node that will not have this problem -- you can follow any of the three steps I gave above to resolve this problem 🙂 

Thanks for filing an issue!

**Comment by connor4312** [comment]
A fix for this issue has now been released in VS Code 1.47.2. If you previously had to opt-out of the new debugger, you should be safe to turn it back on. Thanks again for the report!
