### ISSUE TITLE
Python interactive window no longer working in remote workspace following upgrade to 1.48.2

### ISSUE THREAD

**Issue by robmcc10** [microsoft/vscode#105397]
- VSCode Version: 1.48.2
- OS Version: macOS 10.14.4

Steps to Reproduce:

1. Connect to remote server using remote-ssh extension
2. Attempt to run some python code in python interactive window

This previously worked but after upgrading vs code to 1.48.2 I get the following error:
```

Jupyter notebook failed to launch. 
Error: Traceback (most recent call last):
  File "/home/k1201869/.vscode-server/extensions/ms-python.python-2020.8.103604/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py", line 54, in _decorator
    return func(self, *args, **kwargs)
  File "/home/k1201869/.vscode-server/extensions/ms-python.python-2020.8.103604/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 108, in m_exec_module_observable
    self._start_notebook(args, cwd, env)
  File "/home/k1201869/.vscode-server/extensions/ms-python.python-2020.8.103604/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 150, in _start_notebook
    from notebook import notebookapp as app
  File "/software/system/anaconda/3.6/lib/python3.6/site-packages/notebook/notebookapp.py", line 45, in <module>
    ioloop.install()
  File "/software/system/anaconda/3.6/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'

Failed to run jupyter as observable with args notebook --no-browser --notebook-dir=/tmp/83f78a06-ca86-4715-b0f8-3d0cb54fedb6 --config=/tmp/83f78a06-ca86-4715-b0f8-3d0cb54fedb6/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0



```

PS I can get things to work again by downgrading to VS code 1.43.2
