### ISSUE TITLE
extension crash after update to 1.31.0

### ISSUE THREAD

**Issue by kainstar** [Microsoft/vscode#68218]
Issue Type: <b>Bug</b>

- VSCode Version: 1.31.0
- OS Version: Mac Mojave 10.14.2

after I update vscode's version to 1.31.0, my extension `vscode-astroboy` crashed, then I try debug to find the reason, but my extension host can't start successfully, so I set breakpiont on uncaught Exceptions, then I see some error stack message.

```
Error: Cannot find module 'supports-color'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:874)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/http-proxy-agent/node_modules/debug/src/node.js:29:23)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/http-proxy-agent/node_modules/debug/src/node.js:188:3)
    at Module.t._initNodeRequire.r._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:90)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:874)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/http-proxy-agent/node_modules/debug/src/index.js:9:20)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/http-proxy-agent/node_modules/debug/src/index.js:12:3)
    at Module.t._initNodeRequire.r._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:90)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:874)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/http-proxy-agent/index.js:11:13)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/http-proxy-agent/index.js:113:3)
    at Module.t._initNodeRequire.r._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:90)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:874)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-proxy-agent/index.js:15:22)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-proxy-agent/index.js:114:3)
    at Module.t._initNodeRequire.r._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:90)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at t.load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:449)
    at e.load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:13:866)
    at i (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:28:617)
    at Object.errorback (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:28:738)
    at e.triggerErrorback (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:14:230)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:13:936
    at ReadFileContext.callback (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:660)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:352:13)
```

It looks like a vscode's problem, it can't find `http-proxy-agent`'s dependency `supports-color`. Is my vscode broken?

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.22GB free)|
|Process Argv|-psn_0_618647|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by dbaeumer** [comment]
Could it be that he got this from your install and we don't ship it anymore?

**Comment by USA-RedDragon** [comment]
I can confirm this.

I am running VSCode 1.31.0 as well on Mojave 10.14.3 (18D42) and I went to follow the guide [here](https://code.visualstudio.com/api/get-started/your-first-extension) on making your first extension, and I'm getting the exact same stack trace with the same reproduction steps:

```
Error: Cannot find module 'supports-color'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:874)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/http-proxy-agent/node_modules/debug/src/node.js:29:23)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/http-proxy-agent/node_modules/debug/src/node.js:188:3)
    at Module.t._initNodeRequire.r._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:90)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:874)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/http-proxy-agent/node_modules/debug/src/index.js:9:20)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/http-proxy-agent/node_modules/debug/src/index.js:12:3)
    at Module.t._initNodeRequire.r._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:90)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:874)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/http-proxy-agent/index.js:11:13)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/http-proxy-agent/index.js:113:3)
    at Module.t._initNodeRequire.r._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:90)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:874)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-proxy-agent/index.js:15:22)
    at Object.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-proxy-agent/index.js:114:3)
    at Module.t._initNodeRequire.r._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:90)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at t.load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:449)
    at e.load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:13:866)
    at i (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:28:617)
    at Object.errorback (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:28:738)
    at e.triggerErrorback (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:14:230)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:13:936
    at ReadFileContext.callback (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:660)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:352:13)
```

**Comment by alexandrudima** [comment]
It looks like `vscode-proxy-agent` has a dependency on `debug`, which has an optional dependency on `supports-color` implemented [here](https://github.com/visionmedia/debug/blob/5c7c61dc0df0db4eb5de25707d8cd1b9be1add4f/src/node.js#L26-L28). This will throw each and every time... so breaking on error will break there...

**Comment by chrmarti** [comment]
@alexandrudima That code in the `debug` package catches and ignores the error. There are several versions of `supports-color` in the release's yarn.lock, but none in its ASAR: https://github.com/Microsoft/vscode/blob/release/1.31/yarn.lock#L8382

**Comment by chrmarti** [comment]
@kainstar @USA-RedDragon I only get the debugger to stop there when I enabled breaking on 'All Exceptions' but not when I just enable 'Uncaught Exceptions'. With breaking on all exceptions I see a lot more stacktraces and eventually gave up on clicking 'Continue', but I did not see the extension host crash. The many exceptions are usually ignored because they are part of the normal code flow and most are not in our code, but in some library.

Could you confirm that unchecking breaking on 'All Exceptions' prevents this problem?

**Comment by alexandrudima** [comment]
@chrmarti The ASAR does not trim or remove node modules. Production dependencies are shipped, and then packed in the ASAR. Most likely `supports-color` is not marked as a dependency, so that's why it is not shipped. `yarn.lock` contains dev dependencies as well, so seeing `supports-color` in `yarn.lock` does not mean it should be shipped.

Since we appear to own the module, one option is to delete the code that doesn't do anything from our fork.

**Comment by kainstar** [comment]
@chrmarti Sorry, it's my miss. Not 'Uncaught Exception' but 'All Exception' will print the module not find error stack. If uncheck 'All Exception' option, the extension host will auto close after it started a few seconds, maybe the result of lacking of module `supports-color`.

**Comment by chrmarti** [comment]
@kainstar Does the extension host also auto close when you debug the hello world example or is this something specific to debugging your extension? Is there anything in the console of the debug target (Help > Toggle Developers Tools)?

**Comment by alexandrudima** [comment]
@kainstar I don't think the extension host closes due to a missing `supports-color`, i.e. `supports-color` is missing, but all the code around it is fine and continues to run fine when it is missing (expected).

I think there is something else causing the extension host to crash. Does the extension host run normally when not doing debugging? Can you try disabling your other installed extensions?
