### ISSUE TITLE
Integrated Terminal createNew command throws an error on Insiders

### ISSUE THREAD

**Issue by ZetaHunter** [Microsoft/vscode#11894]
- VSCode Version: 1.6.0-insider [52bceb1](https://github.com/Microsoft/vscode/commit/52bceb1207188ecfe8c5b1fbe841b60df512a08a)
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Open the terminal (using Ctrl + ` or otherwise.)
2. Kill the terminal.
3. Attempt to open it again, notice that cmd does not start again.

### Notes:

This behavior was noticed originally while trying to re-run a python script using Python extension, further testing showed the issue is only with nightly as it doesn't occur on stable.

### Console:
Upon closing first terminal:
```
index.js:23 [uncaught exception]: Error: IPC channel is already disconnectedonError @ index.js:23(anonymous function) @ index.js:90emitOne @ events.js:90emit @ events.js:182window.onerror @ C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\renderer\init.js:107i.globals.onerror @ errorTelemetry.ts:64
index.js:26 Error: IPC channel is already disconnected
    at ChildProcess.target.disconnect (internal/child_process.js:660)
    at Pipe.channel.onread (internal/child_process.js:453)onError @ index.js:26(anonymous function) @ index.js:90emitOne @ events.js:90emit @ events.js:182window.onerror @ C:\Program Files (x86)\Microsoft VS Code Insiders\resources\electron.asar\renderer\init.js:107i.globals.onerror @ errorTelemetry.ts:64
events.js:154 Uncaught Error: IPC channel is already disconnectedtarget.disconnect @ internal/child_process.js:660channel.onread @ internal/child_process.js:453
```

Further attempts to open terminal:
```
threadService.ts:217 [Extension Host] WARNING: Promise with no error callback:62
threadService.ts:217 [Extension Host] Object {exception: null, error: Object, promise: Object, id: 62}
shell.ts:424 Cannot set property 'name' of undefined: TypeError: Cannot set property 'name' of undefined
    at t.createNew (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:96:15100)
    at t.$createTerminal (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:105:7710)
    at t.e.handle (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:104:4494)
    at s (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:50:9560)
    at f (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:50:10237)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ shell.ts:424(anonymous function) @ shell.ts:337e.onUnexpectedError @ errors.ts:68r @ errors.ts:83t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:269f @ ipcRemoteCom.ts:226_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

**Comment by Tyriar** [comment]
Repro'd myself on Insiders using ctrl+shift+backtick, likely caused by #11700 /cc @octref

**Comment by Tyriar** [comment]
Will be fixed when #11839 is merged.
