### ISSUE TITLE
Ctrl+Click doesn't take me to line #, only file top

### ISSUE THREAD

**Issue by ben44496** [microsoft/vscode#146718]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66
- OS Version: Windows 10, remote VM on Ubuntu Linux 

Steps to Reproduce:

1. Try to ctrl-click on code (ie. `mapreduce.c:56:64`)
![Screenshot 2022-04-04 055136](https://user-images.githubusercontent.com/40243203/161529264-74127299-5720-4f7a-80b4-6e1898e0b972.jpg)

2. Only takes you to top of file, not file line number.
![Screenshot 2022-04-04 055136](https://user-images.githubusercontent.com/40243203/161529394-9e03d125-f44a-4df0-9370-fa5b727650f5.jpg)

Expected Outcome:
Takes me to specific line number in the file, not the top of the file.

**Comment by jessicah** [comment]
I can confirm I'm hitting this too, however, it's quite specific in how it manifests. Header files appear to work correctly, but source files do not, from what I can observe.

E.g. in some sample output:
```
                 from /usr/include/c++/11/bits/hashtable.h:35,
                 from /usr/include/c++/11/unordered_set:46,
                 from lists.h:49,
                 from expand.cpp:33:
/usr/include/c++/11/utility:88:12: note: declaration of ‘struct std::tuple_size<PathComponent>’
   88 |     struct tuple_size;
```

CTRL+Click on headers in `/usr/include` work, linking directly to the line; `lists.h` kind of works, although in my case it opens the command palette with the location entered and selected, requiring ENTER to actually go to the location in the file; however, `expand.cpp` does not. It would be nicer if the `lists.h` case behaved like the `/usr/include` cases, not requiring to press ENTER in the command palette.

A simple testcase:
foo.cpp:
```
#include <foo>
```
bar.cpp:
```
#include "foo.cpp"
```

`foo.cpp:1:10: fatal error: foo: No such file or directory`: CTRL+Click does not work.

Rename `foo.cpp` -> `foo.hpp`:

`foo.hpp:1:10: fatal error: foo: No such file or directory`: CTRL+Click works (opening command palette, requiring an extra ENTER to confirm, as noted earlier).

**Comment by ben44496** [comment]
Interesting... it seems yours is selective and mine is basically getting re-routed to the top (possibly failsafe or something)... maybe these are two separate ones? I should probably add that mine was working say roughly 2 weeks ago (I think) so I don't know if it's a new update or something. I didn't get any new extensions since that time I'm pretty sure.

**Comment by dasa-asen** [comment]
I have a similar behavior since updating to 1.66. Two related issues with links.

1. It seems like VS Code now have a new pattern for detecting ctrl+click links in the output. I could previously have: file(row,col). That no longer works but file:row:col works.
2. The file name matching when clicking seems off. If I click a link for a file called io.xml I get the top list showing all files that contain the letters i and o in their file name.

**Comment by ben44496** [comment]
@dasa-asen The 2nd one is because you have multiple files named `io.xml` open in your workspace. VSCode doesn't know which one you want natively so it shows you a list of them with usually the top result being the most recent or most clicked one iirc.

**Comment by dasa-asen** [comment]
@ben44496 thanks, that is correct. But in my case I also get a hit for a file called Diagnostics.xml because it contains both i and o in its name. A couple of more xml files are also listed and all contains i and o in that order. That did not happen before the 1.66 update.

**Comment by ben44496** [comment]
> @ben44496 thanks, that is correct. But in my case I also get a hit for a file called Diagnostics.xml because it contains both i and o in its name. A couple of more xml files are also listed and all contains i and o in that order. That did not happen before the 1.66 update.

Looks like either an option for full matching was changed or somewhere the options parameter for search (similar to the regular text search) was changed... maybe you might have luck looking at a config file for this?

**Comment by olfMombach** [comment]
I have the same behavior (getting thrown in the right file, but to the top of the file) for Python files. I have also only noticed it quite recently. I don't have any selectively working behavior, though; it's always just throwing me to the top. The syntax for those links is always `src/file.py:line:column`

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)? Let us know if not.

**Comment by czlowiek488** [comment]
@Tyriar Where it was fixed?

**Comment by Tyriar** [comment]
Here's a similar duplicate https://github.com/microsoft/vscode/issues/148765 (couldn't find commit after a quick search)
