### ISSUE TITLE
Markdown Preview does not render any text

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#74295]
Issue Type: <b>Bug</b>

Opening the markdown preview, via wither clicking the icon in the top right, or the keyboard with Command-K V (Control-K V on windows), does not show the rendered markdow in the new panel.

Open any Markdown file (.md)
Click the icon or hit the key combo to open the preview, the preview pane is empty.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/13488/58346698-b3fd6d80-7e29-11e9-8475-95592d7191e9.png">

VS Code version: Code - Insiders 1.35.0-insider (5e1f9440d280b0b04cba843df6a0032bf517a2f0, 2019-05-24T05:15:17.681Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.17GB free)|
|Process Argv|-psn_0_1741225|
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
output-colorizer|IBM|0.1.2
Angular2|joh|7.1.6
azure-account|ms-|0.8.4
csharp|ms-|1.19.1
vscode-typescript-tslint-plugin|ms-|1.1.0
debugger-for-chrome|msj|4.11.3
vetur|oct|0.21.0
material-icon-theme|PKi|3.7.0
quicktype|qui|12.0.46
vue-vscode-snippets|sdr|1.6.0
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.6

(3 theme extensions excluded)

</details>

**Comment by jtsom** [comment]
Opening the developer tools, and doing a Refresh Window command, this is displayed in the console:
```
ERR Cannot read property 'resource' of null: TypeError: Cannot read property 'resource' of null
	at Function.revive (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\markdown-language-features\dist\extension.js:1:70054)
	at l.deserializeWebviewPanel (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\markdown-language-features\dist\extension.js:1:66504)
	at u.$deserializeWebviewPanel (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:567:242)
	at d._doInvokeHandler (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:640:1006)
	at d._invokeHandler (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:640:698)
	at d._receiveRequest (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:639:346)
	at d._receiveOneMessage (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:638:141)
	at define.constructor._protocol.onMessage.e (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:636:400)
	at u.fire (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
	at e (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:43:667)
	at u.fire (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
	at a (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:175:911)
	at e (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:175:957)
	at u.fire (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
	at y._receiveMessage (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:184:834)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:116)
	at u.fire (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
	at f.acceptChunk (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:692)
	at define.constructor._register._socket.onData.e (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:44)
	at Socket.t (c:\Users\John Tsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:186:325)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
workbench.main.js:1402   ERR (intermediate value) is not a function: TypeError: (intermediate value) is not a function
    at G.<anonymous> (file:///C:/Users/John Tsombakos/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5501:813)
    at Generator.next (<anonymous>)
    at file:///C:/Users/John Tsombakos/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:34:621
    at new Promise (<anonymous>)
    at n (file:///C:/Users/John Tsombakos/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:34:398)
    at lifecycleService.when.then (file:///C:/Users/John Tsombakos/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5501:699)
    at process._tickCallback (internal/process/next_tick.js:68:7)
﻿
```

**Comment by mjbvz** [comment]
Broken by 4929acf926a938505653ae20eff6fe18577a6044

**Comment by bpasero** [comment]
@mjbvz I cannot reproduce in that insiders version so the revert seems like a flux, can you please test again and then revert the revert if it is unrelated?

![before](https://user-images.githubusercontent.com/900690/58365408-7e599280-7ec4-11e9-96de-6cde1ff485d2.gif)

**Comment by bpasero** [comment]
I just did a code review of that change and really cannot see any issues with it...

**Comment by bpasero** [comment]
Wait, now I see it. Seems to be related to the breadcrumbs being enabled...
