### ISSUE TITLE
Auto import does not work when in Live Share

### ISSUE THREAD

**Issue by bitttttten** [microsoft/vscode#86690]
- VSCode Version: 1.40.2
- OS Version: Mac OS 10.14.6

Steps to Reproduce:

1. Join or Start a Live Share session.
2. Note that the auto imports does not work (the screenshot below usually says "Import 'useStaticQuery' from 'gatsby'".

![Screenshot 2019-12-10 at 21 11 07](https://user-images.githubusercontent.com/19930241/70565087-acb56b80-1b91-11ea-81bc-7de271d20dfb.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please provide example code that demonstrates this issue

**Comment by bitttttten** [comment]
What example code would you like to see? It happens in every file on my project when Live Sharing so I am struggling to give you some demo code. Not meaning to be rude, just trying to understand what you would want to see :)

For example I also tried Live Share after cloning this repo: https://github.com/bitttttten/gatsbty-starter and it was failing to trigger auto import.

**Comment by mjbvz** [comment]
Thanks. It was not clear if the feature never worked or if it was specific to certain projects

**Comment by mjbvz** [comment]
Closing this since we have not seen other user reports. 

If more people report this problem, I'd like the live share team to investigate first so they can tell us what exactly about auto imports isn't working

**Comment by DavidAdaptive** [comment]
Maybe related to that, is that Live Share on web is not having the lightbulb hint to import usings
A c# example is to write:
var sb = new StringBuilder();

Then Visual Studio Code shows a light bulb to give the user the hint to import System.Text namespace. But it doesn't work that way on website, I know it's a preview, so want to clarify if it's just not implemented still

**Comment by danielquintero** [comment]
This is still an issue, autoimport and navigating to module declarations isn't working for collaborators. This makes the collaboration sessions basically ineffective. @mjbvz any chance this could be looked into?

**Comment by liquidg3** [comment]
This is def an issue. As 👆 described, it makes collab sessions difficult at best.

**Comment by thanhle-phd** [comment]
vscode python interactive has this problem too. Please try the followings to reproduce it.
1) create lib.py with the following code
def sayhi():
    return 'Hello'
2) create test.py with the following content
# %% to run in vscode interactive mode
import lib  # this has no problem for sure
print( lib.sayhi() )
# %% --- that's it, then please run the above cell in vscode interactive mode

What will happen?
i) on the host, everything works just fine
ii) on guest, there will be an error: module 'lib' has no attribute 'sayhi'

I have no solution for this problem yet. Any idea?

**Comment by cs11wcq** [comment]
this is still a problem. What is the fix

**Comment by JoacoGDR** [comment]
I'm also having this issue. Can't work if I can't import things

**Comment by Aetherall** [comment]
Also having the issue with all my coworkers

**Comment by kwright02** [comment]
This needs to be re-opened. It's an issue with everyone I know (10+ people)

**Comment by BlakeB415** [comment]
This definitely needs to be reopened.

**Comment by mohammadsadeghforoughi** [comment]
Still not working for me!

**Comment by vladi-strilets** [comment]
Same issue here

**Comment by asoran** [comment]
Still not working on version January 2022 (version 1.64)

**Comment by userlifex** [comment]
It does not work on May 2022

**Comment by alemf** [comment]
Please Reopen this issue

**Comment by josema03** [comment]
This is still a problem (September 2022)

**Comment by manuel-rw** [comment]
I'm also having this issue. Import in Stable, Insider and Web Editor still doesn't work. This is almost un-useable for me

**Comment by gil0mendes** [comment]
I'm having this same issue today. With all the comment above, probably this issue should be re-opened.

**Comment by ggirotto** [comment]
I had this issue today as well, latest vscode version

**Comment by particlesmoke** [comment]
Issue still present.

**Comment by kamilszczepanik** [comment]
I also have this issue... May 2023

**Comment by jssolucoes-e-servicos** [comment]
We are also having this problem here. October 2023

**Comment by mjbvz** [comment]
This is a live share issue so please report it against the Live Share extension. They can follow up with us if there's something that needs to change on the VS Code side
