### ISSUE TITLE
error TS2307: Cannot find module 'tree-sitter' or its corresponding type declarations

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#230497]
I've seen this several times in CI, an update branch fixed it in the past and I assumed somehow a bad commit got into main. However it just happened again when I was on the tip of main so the update branch button wasn't there.

```
> code-oss-dev-build@1.0.0 compile
> ../node_modules/.bin/tsc -p tsconfig.build.json

lib/policies.ts(11,25): error TS2307: Cannot find module 'tree-sitter' or its corresponding type declarations.
lib/policies.ts(319,39): error TS7006: Parameter 'c' implicitly has an 'any' type.
lib/policies.ts(342,39): error TS7006: Parameter 'c' implicitly has an 'any' type.
lib/policies.ts(348,40): error TS7006: Parameter 'c' implicitly has an 'any' type.
lib/policies.ts(490,33): error TS7006: Parameter 'm' implicitly has an 'any' type.
lib/policies.ts(491,47): error TS7006: Parameter 'c' implicitly has an 'any' type.
lib/policies.ts(492,41): error TS7006: Parameter 'c' implicitly has an 'any' type.
lib/policies.ts(493,40): error TS7006: Parameter 'c' implicitly has an 'any' type.
```

https://dev.azure.com/vscode/VSCode/_build/results?buildId=133549&view=logs&j=c7493abb-a1f4-533f-2d24-71780a69f247&t=9396f75f-d8ed-59a9-3621-c73d785709ab&l=27

**Comment by Tyriar** [comment]
I've seen this maybe 10 times over the past month, please fix asap 🙏 

https://dev.azure.com/vscode/VSCode/_build/results?buildId=134430&view=logs&j=c7493abb-a1f4-533f-2d24-71780a69f247&t=9396f75f-d8ed-59a9-3621-c73d785709ab&l=27

**Comment by alexr00** [comment]
I don't know that this is related to the tree sitter work I've done. I just looks like a required dependency isn't specified in the `build` pacakge.json. I've made it required, we'll see if that solves the problem.
