### ISSUE TITLE
Can't launch code-insiders in ubuntu 16.04

### ISSUE THREAD

**Issue by skyfore** [Microsoft/vscode#42393]
- VSCode Version:  1.20.0-1517293131
- OS Version:  Ubuntu 16.04

Steps to Reproduce:

1.  update code-insiders with apt
`Get:1 http://packages.microsoft.com/repos/vscode stable/main amd64 code-insiders amd64 1.20.0-1517293131 [45.9 MB]
`

Does this issue occur when all extensions are disabled?: Yes

```bash
{ errorCode: 'load',
  moduleId: 'iconv-lite',
  neededBy: [ 'vs/base/node/encoding', 'vs/code/node/cli' ],
  detail: 
   { Error: Cannot find module 'iconv-lite'
       at Function.Module._resolveFilename (module.js:470:15)
       at Function.Module._load (module.js:418:25)
       at Module.require (module.js:498:17)
       at require (internal/module.js:20:19)
       at t.load (/usr/share/code-insiders/resources/app/out/vs/loader.js:15:911)
       at e.load (/usr/share/code-insiders/resources/app/out/vs/loader.js:13:465)
       at s (/usr/share/code-insiders/resources/app/out/vs/loader.js:27:811)
       at Object.errorback (/usr/share/code-insiders/resources/app/out/vs/loader.js:27:1003)
       at e.triggerErrorback (/usr/share/code-insiders/resources/app/out/vs/loader.js:13:826)
       at /usr/share/code-insiders/resources/app/out/vs/loader.js:13:535 code: 'MODULE_NOT_FOUND' } }
{ errorCode: 'load',
  moduleId: 'minimist',
  neededBy: [ 'vs/platform/environment/node/argv' ],
  detail: 
   { Error: Cannot find module 'minimist'
       at Function.Module._resolveFilename (module.js:470:15)
       at Function.Module._load (module.js:418:25)
       at Module.require (module.js:498:17)
       at require (internal/module.js:20:19)
       at t.load (/usr/share/code-insiders/resources/app/out/vs/loader.js:15:911)
       at e.load (/usr/share/code-insiders/resources/app/out/vs/loader.js:13:465)
       at s (/usr/share/code-insiders/resources/app/out/vs/loader.js:27:811)
       at Object.errorback (/usr/share/code-insiders/resources/app/out/vs/loader.js:27:1003)
       at e.triggerErrorback (/usr/share/code-insiders/resources/app/out/vs/loader.js:13:826)
       at /usr/share/code-insiders/resources/app/out/vs/loader.js:13:535 code: 'MODULE_NOT_FOUND' } }
```

It means not found modules ?

I tried to run `sudo apt install --reinstall code-insiders`, but not work.

**Comment by chrmarti** [comment]
Also on Mac when starting from the command line. Starting from the dock still works.

**Comment by lighht** [comment]
Doesn't work on Ubuntu 17.10 either.

**Comment by alexandrudima** [comment]
The workaround is to launch `./code-insiders` instead of `./bin/code-insiders`. We are working on pushing out a fix, sorry for the breakage.

**Comment by alexandrudima** [comment]
The fix is now available.

**Comment by NitsanBaleli** [comment]
after `apt-get update && apt-get upgrade` I cannot see a new version yet
still unable to open from terminal

**Comment by chrmarti** [comment]
@NitsanBaleli `https://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/` shows the latest `code-insiders_1.20.0-1517305900_amd64.deb` and I got that when installing. Is packages.microsoft.com/repos/vscode in your apt sources?

**Comment by NitsanBaleli** [comment]
`/etc/apt/sources.list.d/vscode.list`:

### THIS FILE IS AUTOMATICALLY CONFIGURED ###
 # You may comment out this entry, but any other modifications may be lost.
 deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
